# Introduction

The data set comes from Melbourne accident records. The purpose is to try to improve the accident rate from the accident data set.

Therefore, the first step is exploring the data and finding the anomalous and missing values in the data set.


# Read the files into dataframe

In [1]:
import pandas as pd
import glob # search the mutiple paths with the different csv. files
import datetime as dt

In [2]:
# store each file into the files_list
path = r"C:\Users\Mountain\PWC_Test"
all_files = glob.glob(path + "/*.csv")
files_list = []

for name in all_files:
    files_list.append(name)

In [3]:
# build the function to read the csv
def read_csv_file(filename):
    df = pd.read_csv(filename)
    return df

In [4]:
# print of each file's name
print(files_list)

['C:\\Users\\Mountain\\PWC_Test\\ACCIDENT.csv', 'C:\\Users\\Mountain\\PWC_Test\\ACCIDENT_LOCATION.csv', 'C:\\Users\\Mountain\\PWC_Test\\NODE.csv']


In [5]:
# read each file into dataframe
acc_df = read_csv_file(files_list[0]) # read the accident.csv file into dataframe
acc_lo_df = read_csv_file(files_list[1]) # read the accident_location file into dataframe
node_df = read_csv_file(files_list[2]) # read the node file into dataframe

In [6]:
# look at the result on acc_df
acc_df[:5]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
0  T20060000265   20/01/2006     22.10.00              4   
1  T20070034197   18/12/2006     19.30.00              1   
2  T20070035112   14/12/2006     15.55.00              2   
3  T20070036807   20/05/2006     10.00.00              1   
4  T20070038568   12/11/2006     15.00.00              7   

               Accident Type Desc  DAY_OF_WEEK Day Week Description  DCA_CODE  \
0   Collision with a fixed object            6               Friday       171   
1          Collision with vehicle            2               Monday       121   
2               Struck Pedestrian            5             Thursday       109   
3          Collision with vehicle            7             Saturday       142   
4  Fall from or in moving vehicle            1               Sunday       174   

                                     DCA Description DIRECTORY  ...  \
0  LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICL...       NaN  ...   
1              RIGHT THROUGH                               MEL  ...   
2  ANY MANOEUVRE INVOLVING PED NOT INCLUDED IN DC...       MEL  ...   
3             LEAVING PARKING                              MEL  ...   
4  OUT OF CONTROL ON CARRIAGEWAY (ON STRAIGHT)   ...       VCS  ...   

  NO_PERSONS NO_PERSONS_INJ_2 NO_PERSONS_INJ_3 NO_PERSONS_KILLED  \
0          4                0                4                 0   
1          2                0                1                 0   
2          2                1                0                 0   
3          2                0                1                 0   
4          1                0                1                 0   

   NO_PERSONS_NOT_INJ POLICE_ATTEND  ROAD_GEOMETRY   Road Geometry Desc  \
0                   0             2              5  Not at intersection   
1                   1             2              1   Cross intersection   
2                   1             1              5  Not at intersection   
3                   1             2              2       T intersection   
4                   0             2              5  Not at intersection   

   SEVERITY  SPEED_ZONE  
0         3         100  
1         3          60  
2         2          80  
3         3         999  
4         3         888  

[5 rows x 28 columns]

In [7]:
# look at the result on acc_lo_df
acc_lo_df[:5]

ACCIDENT_NO  NODE_ID  ROAD_ROUTE_1   ROAD_NAME ROAD_TYPE    ROAD_NAME_INT  \
0  T20060000010    43078        2090.0      FOSTER    STREET           MCCRAE   
1  T20060000018    29720        5057.0      HALLAM      ROAD  BELGRAVE-HALLAM   
2  T20060000022   203074        9999.0      BROWNS      ROAD         TRUEMANS   
3  T20060000023    55462        2400.0  SPRINGVALE      ROAD      KEYSBOROUGH   
4  T20060000026   202988        9999.0   ELIZABETH    AVENUE        GREENHOOD   

  ROAD_TYPE_INT  DISTANCE_LOCATION DIRECTION_LOCATION  NEAREST_KM_POST  \
0        STREET                0.0                 SW              NaN   
1          ROAD               71.0                  S              NaN   
2          ROAD              210.0                  W              NaN   
3        AVENUE                0.0                  N              NaN   
4      CRESCENT               20.0                  N              NaN   

  OFF_ROAD_LOCATION  
0               NaN  
1               NaN  
2               NaN  
3               NaN  
4               NaN

It found that the accident dataframe and accident location dataframe share the same accident_id. Therefore, these two dataframes can do the inner join approach.

In [8]:
# look at the result on node_df
node_df[:5]

ACCIDENT_NO  NODE_ID NODE_TYPE        AMG_X        AMG_Y  \
0  T20060000010    43078         I  2519154.655  2390265.154   
1  T20060000018    29720         N  2524272.743  2389996.817   
2  T20060000022   203074         N  2487321.693  2345019.925   
3  T20060000023    55462         I  2512734.120  2390214.959   
4  T20060000026   202988         N  2488777.662  2347612.069   

               LGA_NAME          Lga Name All                     Region Name  \
0             DANDENONG             DANDENONG  METROPOLITAN SOUTH EAST REGION   
1                 CASEY                 CASEY  METROPOLITAN SOUTH EAST REGION   
2  MORNINGTON PENINSULA  MORNINGTON PENINSULA  METROPOLITAN SOUTH EAST REGION   
3             DANDENONG    KINGSTON,DANDENONG  METROPOLITAN SOUTH EAST REGION   
4  MORNINGTON PENINSULA  MORNINGTON PENINSULA  METROPOLITAN SOUTH EAST REGION   

   Deg Urban Name       Lat       Long  Postcode No  
0      MELB_URBAN -37.98862  145.21805         3175  
1      MELB_URBAN -37.99092  145.27632         3804  
2  RURAL_VICTORIA -38.39632  144.85489         3939  
3      MELB_URBAN -37.98918  145.14496         3173  
4      MELB_URBAN -38.37299  144.87159         3940

If found the accident location dataframe and node dataframe have the same column which is accident_no and node_type. Then, it may can be mergered by accident_no or node_id.

# Statistic Result

## General check the pattern of each dataset

### Accident dataframe (acc_df)

In [9]:
acc_df.describe()

ACCIDENT_TYPE   DAY_OF_WEEK      DCA_CODE  LIGHT_CONDITION  \
count   54258.000000  54258.000000  54258.000000     54258.000000   
mean        2.264053      3.897803    139.743466         1.890818   
std         2.024974      2.004751     26.510306         1.621712   
min         1.000000      0.000000    100.000000         1.000000   
25%         1.000000      2.000000    120.000000         1.000000   
50%         1.000000      4.000000    130.000000         1.000000   
75%         4.000000      6.000000    171.000000         2.000000   
max         9.000000      7.000000    199.000000         9.000000   

             NODE_ID  NO_OF_VEHICLES    NO_PERSONS  NO_PERSONS_INJ_2  \
count   54258.000000    54258.000000  54258.000000      54258.000000   
mean   202216.874894        1.803752      2.385436          0.329647   
std    122815.544310        0.748534      1.546309          0.587104   
min       -10.000000        1.000000      1.000000          0.000000   
25%     46502.000000        1.000000      2.000000          0.000000   
50%    277362.500000        2.000000      2.000000          0.000000   
75%    302237.250000        2.000000      3.000000          1.000000   
max    327712.000000       14.000000     89.000000         16.000000   

       NO_PERSONS_INJ_3  NO_PERSONS_KILLED  NO_PERSONS_NOT_INJ  POLICE_ATTEND  \
count      54258.000000       54258.000000        54258.000000   54258.000000   
mean           0.913543           0.019002            1.122784       1.290280   
std            0.763322           0.149176            1.354557       0.655738   
min            0.000000           0.000000            0.000000       1.000000   
25%            0.000000           0.000000            0.000000       1.000000   
50%            1.000000           0.000000            1.000000       1.000000   
75%            1.000000           0.000000            1.000000       2.000000   
max           25.000000           4.000000           87.000000       9.000000   

       ROAD_GEOMETRY      SEVERITY    SPEED_ZONE  
count   54258.000000  54258.000000  54258.000000  
mean        3.406926      2.681909    130.215858  
std         1.764163      0.502075    231.491585  
min         1.000000      1.000000     30.000000  
25%         2.000000      2.000000     60.000000  
50%         5.000000      3.000000     60.000000  
75%         5.000000      3.000000     80.000000  
max         9.000000      4.000000    999.000000

In [10]:
acc_df.count()

ACCIDENT_NO             54258
ACCIDENTDATE            54258
ACCIDENTTIME            54258
ACCIDENT_TYPE           54258
Accident Type Desc      54258
DAY_OF_WEEK             54258
Day Week Description    54258
DCA_CODE                54258
DCA Description         54258
DIRECTORY               54231
EDITION                 54231
PAGE                    54231
GRID_REFERENCE_X        54231
GRID_REFERENCE_Y        54231
LIGHT_CONDITION         54258
Light Condition Desc    54258
NODE_ID                 54258
NO_OF_VEHICLES          54258
NO_PERSONS              54258
NO_PERSONS_INJ_2        54258
NO_PERSONS_INJ_3        54258
NO_PERSONS_KILLED       54258
NO_PERSONS_NOT_INJ      54258
POLICE_ATTEND           54258
ROAD_GEOMETRY           54258
Road Geometry Desc      54258
SEVERITY                54258
SPEED_ZONE              54258
dtype: int64

In the accident dataset, it has five columns have the missing value which are DIRECTORY, EDITION, PAGE, GRID_REFERENCE_X, and GRID_REFERENCE_Y.


| Column Name | Definition |
| :----------: | :---------: |
| DIRECTORY   | MEL Melway directory VCD Vic Roads directory.|
| EDITION     | MEL Melway directory VCD Vic Roads directory. e.g. ED30|
| PAGE        | MEL Melway directory VCD Vic Roads directory. e.g. 91A|
| GRID_REFERENCE_X | the grid reference in the x direction of the cell in the street directory used to provide a map reference for the accident. |
| GRID_REFERENCE_Y | the grid reference in the y direction of the cell in the street directory used to provide a map reference for the accident. |

In [11]:
# look at these five columns specifically

check_list = ["DIRECTORY", "EDITION", "PAGE", "GRID_REFERENCE_X", "GRID_REFERENCE_Y"]

for col in check_list:
    print(acc_df.groupby(col)[col].count())

DIRECTORY
        4268
MEL    37557
VCD        7
VCS    12399
Name: DIRECTORY, dtype: int64
EDITION
         4268
40      35525
43       2030
9       12406
ED35        2
Name: EDITION, dtype: int64
PAGE
        4268
1          7
10       200
100      291
100A     119
        ... 
95       131
96       615
97       491
98       211
99       193
Name: PAGE, Length: 585, dtype: int64
GRID_REFERENCE_X
     4268
A    4215
B    4602
C    4797
D    4795
E    4745
F    5061
G    4955
H    5176
J    4544
K    4134
L     298
M     257
N     336
O     303
P     364
Q     336
R     320
S     223
T     230
U     198
V      74
Name: GRID_REFERENCE_X, dtype: int64
GRID_REFERENCE_Y
      4268
1     3463
10    3592
11    3844
12    3384
13      76
14       9
2     3935
3     4132
4     4526
5     4583
6     4577
7     4526
8     4631
9     4685
Name: GRID_REFERENCE_Y, dtype: int64


It indicates that the majority data comes from MEL and VCS. Minority accident data comes from VCD. Also, the edition column shows that it has numberous data happends in 40 and 9, and less data occurs in ED35. Another three columns don't provide very useful information to analysis the pattern of those accidents. Therefore, these five columns will be removed.

In summary, it has several finding after analysing the accident dataset.
1. the **accident_type** column: it indicates that the majority (at least) accident type is 1 which means collision with vehicle.

2. the **day_of_week** column: it should be double-check in the column becuase the minimum number of day_of_week should be 1 not 0. Also, it can be checked with the day_week_description column.

3. the **dca_code** column: it shows that the maximum value is 199 which is correct because it means that unknown no details on manoeuvres of road users in accident.

4. the **light_condition** column: it shows that the majority accident happend in day.

5. the **no_of_vehicles** column: it indicates that the maximum vehicles accident involved was 14.

6. the **node_id** column: it shows that the minimum value is -10, however, the description indicates that the node_id starts with 1 and incremented by one when a new accident location is indentified.

7. the **no_persons** column: it shows that the maximum value is 89. In other words, it has 89 persons involved into the accident. It needs to double-check does the value is correct, or it actually had this serious accident event.

8. the **no_persons_killed** column: it indicates that it had four people die in the accident and this was the serious accident in this dataset.

9. the **no_persons_not_inj** column: it indicates that it had 9 people did not suffer from the injury which might prove the answer of no_persons column of 89 persons involved in the accident.

10. the **police_attend** column: it shows that it had the maximum number of 9 and it means that the accident event did not indicate that it was a police attended.

11. the **road_geometry** column: it shows that the maximum number was 9 which means unknown accident situation.

12. the **speed_zone** column: it shows that the maximum number was 999 but it does not mean the maximum speed in the accident was 999. The nubmer of 999 means unknown the speed number in the accident.

### Accident location dataframe (acc_lo_df)

In [12]:
acc_lo_df

ACCIDENT_NO  NODE_ID  ROAD_ROUTE_1     ROAD_NAME ROAD_TYPE  \
0       T20060000010    43078        2090.0        FOSTER    STREET   
1       T20060000018    29720        5057.0        HALLAM      ROAD   
2       T20060000022   203074        9999.0        BROWNS      ROAD   
3       T20060000023    55462        2400.0    SPRINGVALE      ROAD   
4       T20060000026   202988        9999.0     ELIZABETH    AVENUE   
...              ...      ...           ...           ...       ...   
164784  T20180003952    50007        9999.0       KILGOUR    STREET   
164785  T20180003965    36037        9999.0      GLENLYON      ROAD   
164786  T20180003971   327628        5781.0  MT DANDENONG      ROAD   
164787  T20180004017   327667        2800.0       PRINCES   HIGHWAY   
164788  T20180004030      397        5878.0    ST GEORGES      ROAD   

          ROAD_NAME_INT ROAD_TYPE_INT  DISTANCE_LOCATION DIRECTION_LOCATION  \
0                MCCRAE        STREET                0.0                 SW   
1       BELGRAVE-HALLAM          ROAD               71.0                  S   
2              TRUEMANS          ROAD              210.0                  W   
3           KEYSBOROUGH        AVENUE                0.0                  N   
4             GREENHOOD      CRESCENT               20.0                  N   
...                 ...           ...                ...                ...   
164784            YARRA        STREET                0.0                  E   
164785            LYGON        STREET                0.0                  W   
164786           DUBLIN          ROAD               35.0                  E   
164787       CORIO QUAY          ROAD               55.0                 NW   
164788           MILLER        STREET                0.0                 SW   

        NEAREST_KM_POST OFF_ROAD_LOCATION  
0                   NaN               NaN  
1                   NaN               NaN  
2                   NaN               NaN  
3                   NaN               NaN  
4                   NaN               NaN  
...                 ...               ...  
164784              NaN               NaN  
164785              NaN               NaN  
164786              NaN               NaN  
164787              NaN               NaN  
164788              NaN               NaN  

[164789 rows x 11 columns]

In [13]:
acc_lo_df.describe()

NODE_ID   ROAD_ROUTE_1  DISTANCE_LOCATION  NEAREST_KM_POST
count  164789.000000  163913.000000      163913.000000           4278.0
mean   161455.360418    6272.846595         130.126884              0.0
std    111355.684234    3110.580864         391.138150              0.0
min       -10.000000      -1.000000          -1.000000              0.0
25%     42723.000000    2880.000000           0.000000              0.0
50%    210679.000000    5770.000000          13.000000              0.0
75%    261147.000000    9999.000000          80.000000              0.0
max    327712.000000    9999.000000       17275.000000              0.0

In summary, it has few findings after analysing the statistic number in the accident dataset.

1. the **node_id** column: it shows that the minimum value is -10, however, the description indicates that the node_id starts with 1 and incremented by one when a new accident location is indentified. And this result is the same in the accident dataset.

2. the **road_route_1** column: it shows that the minimum value is -1, however, the description indicates that the road_route_1 value only including 2000-2999, 3000-3999, 4000-4999, 5000-5999, 7000-7999, and 9999. There is not descriping the value presenting -1.

3. the **distance_location** column: it shows that the minimum value is -1. The description indicates that the distance_location means the distance (metres) of the accident. However, the distance should not be indicating the -1, which means this number is anonymous.

In [14]:
acc_lo_df.count()

ACCIDENT_NO           164789
NODE_ID               164789
ROAD_ROUTE_1          163913
ROAD_NAME             163813
ROAD_TYPE             162066
ROAD_NAME_INT         163498
ROAD_TYPE_INT         162206
DISTANCE_LOCATION     163913
DIRECTION_LOCATION    163913
NEAREST_KM_POST         4278
OFF_ROAD_LOCATION      20443
dtype: int64

There are two columns having numberous missing value in the accident location dataset. 

These two columns mean:

| Column Name | Definition |
| :----------: | :---------: |
| NEAREST_KM_POST | The distance (in metres) of the accident to the nearest or closest kilometre post.|
| OFF_ROAD_LOCATION | The name of the closest landmark or marker to the accident. |

These two columns do not have the significant impact to analysis the accident event, therefore, these two columns will be removed.

### Node dataframe (node_df)

In [15]:
# look at the statistic data in the node dataframe
node_df.describe()

NODE_ID         AMG_X         AMG_Y            Lat  \
count  166602.000000  1.666020e+05  1.666020e+05  166602.000000   
mean   161848.263892  2.498054e+06  2.420624e+06     -37.712474   
std    111057.582820  7.222472e+04  6.306460e+04       0.571074   
min         4.000000  2.129297e+06  2.273614e+06     -39.032320   
25%     42926.000000  2.488541e+06  2.394272e+06     -37.951667   
50%    210795.500000  2.501675e+06  2.409205e+06     -37.817900   
75%    261288.750000  2.518260e+06  2.421547e+06     -37.706100   
max    327712.000000  2.920148e+06  2.818209e+06     -34.062380   

                Long    Postcode No  
count  166602.000000  166602.000000  
mean      144.979116    3310.207422  
std         0.813129     302.772622  
min       140.966180    3000.000000  
25%       144.869902    3074.000000  
50%       145.019040    3175.000000  
75%       145.207580    3550.000000  
max       149.757470    3996.000000

In the node datafrmae, it looks like that the dataset may not contains the anonymous value.

In [16]:
node_df.count()

ACCIDENT_NO       166602
NODE_ID           166602
NODE_TYPE         166602
AMG_X             166602
AMG_Y             166602
LGA_NAME          166602
Lga Name All      166602
Region Name       166602
Deg Urban Name    166602
Lat               166602
Long              166602
Postcode No       166602
dtype: int64

## Check the unique id

In [17]:
# check the accident_no is the unique id or not in the acc_df dataframe
accid_uni = acc_df["ACCIDENT_NO"].value_counts()
accid_uni[accid_uni > 1]

Series([], Name: ACCIDENT_NO, dtype: int64)

In [18]:
# check the node_id is the unique id or not in the acc_df dataframe
nodeid_uni = acc_df["NODE_ID"].value_counts()
nodeid_uni[nodeid_uni > 1]

36335     26
43631     23
36370     23
10592     23
40894     19
          ..
321653     2
266784     2
40803      2
57147      2
40012      2
Name: NODE_ID, Length: 4766, dtype: int64

In [19]:
# check the acc_lo_uni is the unique id or not in the acc_lo_df dataframe
acc_lo_uni = acc_lo_df["ACCIDENT_NO"].value_counts()
acc_lo_uni[acc_lo_uni > 1]

Series([], Name: ACCIDENT_NO, dtype: int64)

It shows that the accident_no is the unique id column can be merged. However, the node_id shows that it had been used repeatedly depending on the accident location. So, for the security purpose, it will use the accident_no to merge the table.

In [20]:
# double-check the node_df_uni is the unique id or not in the node_df dataframe
node_df_uni = node_df["ACCIDENT_NO"].value_counts()
node_df_uni = node_df_uni[node_df_uni > 1]
node_df_uni

T20120011767    3
T20070022419    3
T20130026885    3
T20110008275    3
T20140020930    3
               ..
T20070007607    2
T20140000102    2
T20110040283    2
T20120008511    2
T20060039267    2
Name: ACCIDENT_NO, Length: 2675, dtype: int64

For the accident_no data, it should be defining as the unique ID. However, in the node_df, it shows the duplicates accident_no. Therefore, it should be considering does the data has the existing the duplicate rows.

## Deal with the duplicate rows

In [21]:
# store the duplicate accident_no
node_df_dict = dict(node_df_uni)
node_accid_list = []

for keys, values in node_df_dict.items():
    node_accid_list.append(keys)

In [22]:
len(node_accid_list) * 0.25

668.75

In [23]:
# to run the first ten list for looking the duplicate problem

for index in range(0, 11):
    print("The accident id is:", node_accid_list[index])
    print(node_df[node_df["ACCIDENT_NO"] == node_accid_list[index]])
    print("------------------------------------------------")

The accident id is: T20120011767
        ACCIDENT_NO  NODE_ID NODE_TYPE        AMG_X        AMG_Y  LGA_NAME  \
87559  T20120011767    24437         I  2538376.485  2381942.623  CARDINIA   
87560  T20120011767    24437         I  2538376.485  2381942.623  CARDINIA   
87561  T20120011767    24437         I  2538376.485  2381942.623  CARDINIA   

      Lga Name All                     Region Name  Deg Urban Name     Lat  \
87559     CARDINIA  METROPOLITAN SOUTH EAST REGION  RURAL_VICTORIA -38.063   
87560     CARDINIA  METROPOLITAN SOUTH EAST REGION    SMALL_CITIES -38.063   
87561     CARDINIA  METROPOLITAN SOUTH EAST REGION     SMALL_TOWNS -38.063   

           Long  Postcode No  
87559  145.4373         3809  
87560  145.4373         3809  
87561  145.4373         3809  
------------------------------------------------
The accident id is: T20070022419
        ACCIDENT_NO  NODE_ID NODE_TYPE        AMG_X        AMG_Y  LGA_NAME  \
19783  T20070022419    24437         I  2538376.485  2381

In [24]:
# to run the ten rows which is nearby the number of 25% rows
i025 = int(len(node_accid_list) * 0.25)

i025_list = []

for num in range(0,6):
    num = i025 + num
    i025_list.append(num)
    num_1 = i025 * 2 - num
    i025_list.append(num_1)

i025_list = sorted(list(set(i025_list)))

for index in range(0, 11):
    print("The accident id is:", node_accid_list[i025_list[index]])
    print(node_df[node_df["ACCIDENT_NO"] == node_accid_list[i025_list[index]]])
    print("------------------------------------------------")

The accident id is: T20180000417
         ACCIDENT_NO  NODE_ID NODE_TYPE        AMG_X        AMG_Y   LGA_NAME  \
165652  T20180000417    29420         I  2496479.808  2409044.898  MELBOURNE   
165653  T20180000417    29420         I  2496479.808  2409044.898  MELBOURNE   

       Lga Name All                     Region Name Deg Urban Name       Lat  \
165652    MELBOURNE  METROPOLITAN NORTH WEST REGION  MELBOURNE_CBD -37.81961   
165653    MELBOURNE  METROPOLITAN NORTH WEST REGION     MELB_URBAN -37.81961   

             Long  Postcode No  
165652  144.96002         3000  
165653  144.96002         3000  
------------------------------------------------
The accident id is: T20160007440
         ACCIDENT_NO  NODE_ID NODE_TYPE        AMG_X        AMG_Y LGA_NAME  \
143119  T20160007440   301819         N  2462828.098  2427549.109   MELTON   
143120  T20160007440   301819         N  2462828.098  2427549.109   MELTON   

       Lga Name All                     Region Name  Deg Urban Name  

In [25]:
# to run the ten rows which is nearby the number of 75% rows
i075 = int(len(node_accid_list) * 0.75)

i075_list = []

for num in range(0,6):
    num = i075 + num
    i075_list.append(num)
    num_1 = i075 * 2 - num
    i075_list.append(num_1)

i075_list = sorted(list(set(i075_list)))

for index in range(0, 11):
    print("The accident id is:", node_accid_list[i075_list[index]])
    print(node_df[node_df["ACCIDENT_NO"] == node_accid_list[i075_list[index]]])
    print("------------------------------------------------")

The accident id is: T20060006928
       ACCIDENT_NO  NODE_ID NODE_TYPE        AMG_X        AMG_Y  \
1922  T20060006928    44000         I  2515081.527  2362535.489   
1923  T20060006928    44000         I  2515081.527  2362535.489   

                  LGA_NAME          Lga Name All  \
1922  MORNINGTON PENINSULA  MORNINGTON PENINSULA   
1923  MORNINGTON PENINSULA  MORNINGTON PENINSULA   

                         Region Name  Deg Urban Name       Lat       Long  \
1922  METROPOLITAN SOUTH EAST REGION      MELB_URBAN -38.23851  145.17225   
1923  METROPOLITAN SOUTH EAST REGION  RURAL_VICTORIA -38.23851  145.17225   

      Postcode No  
1922         3912  
1923         3912  
------------------------------------------------
The accident id is: T20100027589
        ACCIDENT_NO  NODE_ID NODE_TYPE        AMG_X        AMG_Y   LGA_NAME  \
61871  T20100027589    34666         N  2495796.912  2409560.074  MELBOURNE   
61872  T20100027589    34666         N  2495796.912  2409560.074  MELBOURNE 

Those results indicate that the accident id has the duplicate problem because of the column name "Deg Urban Name". On each row, the deg_urban_name shows that it has two or more value to descrip each accident ID. For instance, "MELBOURNE_CBD", "SMALL_TOWNS", "MELB_URBAN", and "RURAL_VICTORIA". However, this column does not show on the data dictonary. In here, it assumes that the column may not cause any significant impact after removing it. Therefore, it will be removed.


In [26]:
# Remove the column
del node_df["Deg Urban Name"]

In [27]:
# deal with the duplicate problem after removing the Deg Urban Name column
node_df = node_df[~node_df.duplicated(["ACCIDENT_NO"])]
node_df[:5]

ACCIDENT_NO  NODE_ID NODE_TYPE        AMG_X        AMG_Y  \
0  T20060000010    43078         I  2519154.655  2390265.154   
1  T20060000018    29720         N  2524272.743  2389996.817   
2  T20060000022   203074         N  2487321.693  2345019.925   
3  T20060000023    55462         I  2512734.120  2390214.959   
4  T20060000026   202988         N  2488777.662  2347612.069   

               LGA_NAME          Lga Name All                     Region Name  \
0             DANDENONG             DANDENONG  METROPOLITAN SOUTH EAST REGION   
1                 CASEY                 CASEY  METROPOLITAN SOUTH EAST REGION   
2  MORNINGTON PENINSULA  MORNINGTON PENINSULA  METROPOLITAN SOUTH EAST REGION   
3             DANDENONG    KINGSTON,DANDENONG  METROPOLITAN SOUTH EAST REGION   
4  MORNINGTON PENINSULA  MORNINGTON PENINSULA  METROPOLITAN SOUTH EAST REGION   

        Lat       Long  Postcode No  
0 -37.98862  145.21805         3175  
1 -37.99092  145.27632         3804  
2 -38.39632  144.85489         3939  
3 -37.98918  145.14496         3173  
4 -38.37299  144.87159         3940

In [28]:
# double-check the node_df_uni is the unique id or not in the node_df dataframe
node_df_uni = node_df["ACCIDENT_NO"].value_counts()
node_df_uni = node_df_uni[node_df_uni > 1]
node_df_uni

Series([], Name: ACCIDENT_NO, dtype: int64)

After removing the duplicate rows, the accident number shows taht it is the unique ID.

In [29]:
# count of each column's data
node_df.count()

ACCIDENT_NO     163913
NODE_ID         163913
NODE_TYPE       163913
AMG_X           163913
AMG_Y           163913
LGA_NAME        163913
Lga Name All    163913
Region Name     163913
Lat             163913
Long            163913
Postcode No     163913
dtype: int64

After counting the result, it shows that each column does not contain the missing value.

## Deal with the anonymous problems

## 1. Check with the day_of_week and day_week_description in the acc_df

In [30]:
acc_df[:5]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
0  T20060000265   20/01/2006     22.10.00              4   
1  T20070034197   18/12/2006     19.30.00              1   
2  T20070035112   14/12/2006     15.55.00              2   
3  T20070036807   20/05/2006     10.00.00              1   
4  T20070038568   12/11/2006     15.00.00              7   

               Accident Type Desc  DAY_OF_WEEK Day Week Description  DCA_CODE  \
0   Collision with a fixed object            6               Friday       171   
1          Collision with vehicle            2               Monday       121   
2               Struck Pedestrian            5             Thursday       109   
3          Collision with vehicle            7             Saturday       142   
4  Fall from or in moving vehicle            1               Sunday       174   

                                     DCA Description DIRECTORY  ...  \
0  LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICL...       NaN  ...   
1              RIGHT THROUGH                               MEL  ...   
2  ANY MANOEUVRE INVOLVING PED NOT INCLUDED IN DC...       MEL  ...   
3             LEAVING PARKING                              MEL  ...   
4  OUT OF CONTROL ON CARRIAGEWAY (ON STRAIGHT)   ...       VCS  ...   

  NO_PERSONS NO_PERSONS_INJ_2 NO_PERSONS_INJ_3 NO_PERSONS_KILLED  \
0          4                0                4                 0   
1          2                0                1                 0   
2          2                1                0                 0   
3          2                0                1                 0   
4          1                0                1                 0   

   NO_PERSONS_NOT_INJ POLICE_ATTEND  ROAD_GEOMETRY   Road Geometry Desc  \
0                   0             2              5  Not at intersection   
1                   1             2              1   Cross intersection   
2                   1             1              5  Not at intersection   
3                   1             2              2       T intersection   
4                   0             2              5  Not at intersection   

   SEVERITY  SPEED_ZONE  
0         3         100  
1         3          60  
2         2          80  
3         3         999  
4         3         888  

[5 rows x 28 columns]

The correct information:

| DAY_OF_WEEK | Day Week Description |
| :----------: | :---------: |
| 1 | Sunday |
| 2 | Monday |
| 3 | Tuesday |
| 4 | Wednesday |
| 5 | Thursday |
| 6 | Friday |
| 7 | Saturday |

In [31]:
# check the accident date such as the correct year, month, and date
acc_df[["Day", "Month", "Year"]] = acc_df["ACCIDENTDATE"].str.split("/", expand=True).astype(int)

In [32]:
# check the day does not over the 30 when the month is 4, 6, 9, 11
mon1 = [4, 6, 9, 11]

for mon in mon1:
    if len(acc_df[(acc_df["Day"] > 30) & (acc_df["Month"] == mon)]) == 0:
        print("It does not have the anoymous day in the month of %s" % mon)

It does not have the anoymous day in the month of 4
It does not have the anoymous day in the month of 6
It does not have the anoymous day in the month of 9
It does not have the anoymous day in the month of 11


In [33]:
# check the day does not over the 30 when the month is 1, 3, 5, 7, 8, 10, 12
mon2 = [1, 3, 5, 7, 8, 10, 12]

for mon in mon2:
    if len(acc_df[(acc_df["Day"] > 31) & (acc_df["Month"] == mon)]) == 0:
        print("It does not have the anoymous day in the month of %s" % mon)

It does not have the anoymous day in the month of 1
It does not have the anoymous day in the month of 3
It does not have the anoymous day in the month of 5
It does not have the anoymous day in the month of 7
It does not have the anoymous day in the month of 8
It does not have the anoymous day in the month of 10
It does not have the anoymous day in the month of 12


In [34]:
# check the day does not over the 30 when the month is 2
acc_df[(acc_df["Day"] > 30) & (acc_df["Month"] == 2)]

Empty DataFrame
Columns: [ACCIDENT_NO, ACCIDENTDATE, ACCIDENTTIME, ACCIDENT_TYPE, Accident Type Desc, DAY_OF_WEEK, Day Week Description, DCA_CODE, DCA Description, DIRECTORY, EDITION, PAGE, GRID_REFERENCE_X, GRID_REFERENCE_Y, LIGHT_CONDITION, Light Condition Desc, NODE_ID, NO_OF_VEHICLES, NO_PERSONS, NO_PERSONS_INJ_2, NO_PERSONS_INJ_3, NO_PERSONS_KILLED, NO_PERSONS_NOT_INJ, POLICE_ATTEND, ROAD_GEOMETRY, Road Geometry Desc, SEVERITY, SPEED_ZONE, Day, Month, Year]
Index: []

[0 rows x 31 columns]

In [35]:
# check the month does not over the 12 or less than 1
acc_df[(acc_df["Month"] > 12) & (acc_df["Month"] < 1)]

Empty DataFrame
Columns: [ACCIDENT_NO, ACCIDENTDATE, ACCIDENTTIME, ACCIDENT_TYPE, Accident Type Desc, DAY_OF_WEEK, Day Week Description, DCA_CODE, DCA Description, DIRECTORY, EDITION, PAGE, GRID_REFERENCE_X, GRID_REFERENCE_Y, LIGHT_CONDITION, Light Condition Desc, NODE_ID, NO_OF_VEHICLES, NO_PERSONS, NO_PERSONS_INJ_2, NO_PERSONS_INJ_3, NO_PERSONS_KILLED, NO_PERSONS_NOT_INJ, POLICE_ATTEND, ROAD_GEOMETRY, Road Geometry Desc, SEVERITY, SPEED_ZONE, Day, Month, Year]
Index: []

[0 rows x 31 columns]

In [36]:
# group the year to look at the how many rows at each year
acc_df.groupby("Year")["Year"].count()

Year
2006        9
2014    14249
2015    14417
2016    14294
2017    11288
2036        1
Name: Year, dtype: int64

After looking at the year's data, it shows the anoymous data which is 2036. Also, in 2006, it has only few data which is 9, and it is not having the sense to see the trend during this data comparing with other years.

Therefore, these ten rows will be removed.

In [37]:
# removed the anonymous data in the acc_df

idx = acc_df[(acc_df["Year"] == 2006) | (acc_df["Year"] == 2036)].index.values

for index in idx:
    acc_df.drop([index], inplace = True)

In [38]:
# delete the column of year, month, and day
del acc_df["Year"]
del acc_df["Month"]
del acc_df["Day"]

In [39]:
# change the ACCIDENTDATE data type from object to datetiem
acc_df["ACCIDENTDATE"] = pd.to_datetime(acc_df["ACCIDENTDATE"])

In [40]:
# add the new column of correct_dayofweek to check the day_of_week and day_week_description data
acc_df["correct_dayofweek"] = acc_df["ACCIDENTDATE"].dt.dayofweek

In [41]:
# change the value in correct_dayofweek column from number to string
week_day = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

for index in range(0, 7):
    acc_df.loc[acc_df["correct_dayofweek"] == index, "correct_dayofweek"] = week_day[index]

### Updating the data on Sunday

#### On the day_of_week perspective

In [42]:
# check the incorrect data on sunday
acc_df[(acc_df["DAY_OF_WEEK"] == 1) & (acc_df["Day Week Description"] != "Sunday") & 
       (acc_df["Day Week Description"] == acc_df["correct_dayofweek"])]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
545    T20140001272   2014-01-20     17.30.00              1   
560    T20140001304   2014-01-13     08.30.00              1   
785    T20140001761   2014-01-27     10.55.00              4   
833    T20140001854   2014-01-27     19.45.00              1   
1592   T20140003311   2014-02-17     12.12.00              1   
...             ...          ...          ...            ...   
54060  T20170024647   2017-12-25     19.38.00              2   
54061  T20170024653   2017-12-25     23.45.00              1   
54063  T20170024662   2017-12-25     16.30.00              1   
54087  T20170024716   2017-12-25     13.30.00              6   
54187  T20180000025   2017-12-25     18.30.00              2   

                      Accident Type Desc  DAY_OF_WEEK Day Week Description  \
545               Collision with vehicle            1               Monday   
560               Collision with vehicle            1               Monday   
785        Collision with a fixed object            1               Monday   
833               Collision with vehicle            1               Monday   
1592              Collision with vehicle            1               Monday   
...                                  ...          ...                  ...   
54060                  Struck Pedestrian            1               Monday   
54061             Collision with vehicle            1               Monday   
54063             Collision with vehicle            1               Monday   
54087  Vehicle overturned (no collision)            1               Monday   
54187                  Struck Pedestrian            1               Monday   

       DCA_CODE                                    DCA Description DIRECTORY  \
545         121              RIGHT THROUGH                               MEL   
560         130     REAR END(VEHICLES IN SAME LANE)                      MEL   
785         173  RIGHT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHIC...       MEL   
833         130     REAR END(VEHICLES IN SAME LANE)                      MEL   
1592        120         HEAD ON (NOT OVERTAKING)                         MEL   
...         ...                                                ...       ...   
54060       107  PED ON FOOTHPATH STRUCK BY VEHENTERING/LEAVING...       MEL   
54061       120         HEAD ON (NOT OVERTAKING)                         MEL   
54063       130     REAR END(VEHICLES IN SAME LANE)                      MEL   
54087       170         OFF CARRIAGEWAY TO LEFT                          MEL   
54187       102  FAR SIDE. PED HIT BY VEHICLE FROM THE LEFT    ...       MEL   

       ... NO_PERSONS_INJ_2 NO_PERSONS_INJ_3 NO_PERSONS_KILLED  \
545    ...                0                2                 0   
560    ...                0                1                 0   
785    ...                2                0                 0   
833    ...                1                0                 0   
1592   ...                0                2                 0   
...    ...              ...              ...               ...   
54060  ...                1                0                 0   
54061  ...                0                1                 0   
54063  ...                0                2                 0   
54087  ...                1                0                 0   
54187  ...                0                1                 0   

      NO_PERSONS_NOT_INJ  POLICE_ATTEND ROAD_GEOMETRY   Road Geometry Desc  \
545                    2              1             2       T intersection   
560                    1              1             5  Not at intersection   
785                    3              1             5  Not at intersection   
833                   10              1             5  Not at intersection   
1592                   1              1             2       T intersection   
...                  ...            ...           ...                  ...   
54

Those data indicates the day_of_week should be correct to the right value which is 2 because the 2 means the Monday and the date is exactly Monday.

In [43]:
# update the data on from 1 to 2 (day_of_week)
acc_df.loc[(acc_df["DAY_OF_WEEK"] == 1) & (acc_df["Day Week Description"] != "Sunday") & 
           (acc_df["Day Week Description"] == acc_df["correct_dayofweek"]), "DAY_OF_WEEK"]  = 2

In [44]:
# double-check after updating the data
acc_df[(acc_df["DAY_OF_WEEK"] == 1) & (acc_df["Day Week Description"] != "Sunday") & 
       (acc_df["Day Week Description"] == acc_df["correct_dayofweek"])]

Empty DataFrame
Columns: [ACCIDENT_NO, ACCIDENTDATE, ACCIDENTTIME, ACCIDENT_TYPE, Accident Type Desc, DAY_OF_WEEK, Day Week Description, DCA_CODE, DCA Description, DIRECTORY, EDITION, PAGE, GRID_REFERENCE_X, GRID_REFERENCE_Y, LIGHT_CONDITION, Light Condition Desc, NODE_ID, NO_OF_VEHICLES, NO_PERSONS, NO_PERSONS_INJ_2, NO_PERSONS_INJ_3, NO_PERSONS_KILLED, NO_PERSONS_NOT_INJ, POLICE_ATTEND, ROAD_GEOMETRY, Road Geometry Desc, SEVERITY, SPEED_ZONE, correct_dayofweek]
Index: []

[0 rows x 29 columns]

#### On the Day Week Description perspective

In [45]:
# check the incorrect data on sunday
acc_df[(acc_df["DAY_OF_WEEK"] == 1) & (acc_df["correct_dayofweek"] == "Sunday") 
       & (acc_df["Day Week Description"] != "Sunday")]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
135    T20140000331   2014-06-01     13.32.00              1   
1049   T20140002255   2014-03-02     16.25.00              1   
1057   T20140002267   2014-03-02     11.44.00              1   
12724  T20140024879   2014-01-12     08.30.00              1   
12726  T20140024886   2014-01-12     12.50.00              1   
...             ...          ...          ...            ...   
53659  T20170023677   2017-11-12     19.00.00              1   
53664  T20170023686   2017-11-12     17.25.00              1   
53668  T20170023699   2017-11-12     23.32.00              4   
53679  T20170023716   2017-11-12     08.45.00              1   
53702  T20170023801   2017-11-12     17.00.00              1   

                  Accident Type Desc  DAY_OF_WEEK Day Week Description  \
135           Collision with vehicle            1               Monday   
1049          Collision with vehicle            1               Monday   
1057          Collision with vehicle            1               Monday   
12724         Collision with vehicle            1               Monday   
12726         Collision with vehicle            1               Monday   
...                              ...          ...                  ...   
53659         Collision with vehicle            1               Monday   
53664         Collision with vehicle            1               Monday   
53668  Collision with a fixed object            1               Monday   
53679         Collision with vehicle            1               Monday   
53702         Collision with vehicle            1               Monday   

       DCA_CODE                                    DCA Description DIRECTORY  \
135         130     REAR END(VEHICLES IN SAME LANE)                      MEL   
1049        130     REAR END(VEHICLES IN SAME LANE)                      MEL   
1057        130     REAR END(VEHICLES IN SAME LANE)                      MEL   
12724       121              RIGHT THROUGH                               MEL   
12726       121              RIGHT THROUGH                               VCS   
...         ...                                                ...       ...   
53659       110    CROSS TRAFFIC(INTERSECTIONS ONLY)                     MEL   
53664       130     REAR END(VEHICLES IN SAME LANE)                      MEL   
53668       171  LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICL...       MEL   
53679       130     REAR END(VEHICLES IN SAME LANE)                      VCS   
53702       130     REAR END(VEHICLES IN SAME LANE)                      MEL   

       ... NO_PERSONS_INJ_2 NO_PERSONS_INJ_3 NO_PERSONS_KILLED  \
135    ...                0                1                 0   
1049   ...                0                1                 0   
1057   ...                0                1                 0   
12724  ...                0                1                 0   
12726  ...                0                1                 0   
...    ...              ...              ...               ...   
53659  ...                0                1                 0   
53664  ...                0                2                 0   
53668  ...                0                1                 0   
53679  ...                0                1                 0   
53702  ...                0                2                 0   

      NO_PERSONS_NOT_INJ  POLICE_ATTEND ROAD_GEOMETRY     Road Geometry Desc  \
135                    1              1             2         T intersection   
1049                   1              1             1     Cross intersection   
1057                   1              2             1     Cross intersection   
12724                  1              1             4  Multiple intersection   
12726                  2              1             2         T intersection   
...                  ...            ...           ...                    ...   
53659                  1            

In [46]:
# update the data on from monday to sunday (Day Week Description)
acc_df.loc[(acc_df["DAY_OF_WEEK"] == 1) & (acc_df["correct_dayofweek"] == "Sunday") 
           & (acc_df["Day Week Description"] != "Sunday"), "Day Week Description"]  = "Sunday"

In [47]:
# double-check after updating the data
acc_df[(acc_df["DAY_OF_WEEK"] == 1) & (acc_df["correct_dayofweek"] == "Sunday") 
       & (acc_df["Day Week Description"] != "Sunday")]

Empty DataFrame
Columns: [ACCIDENT_NO, ACCIDENTDATE, ACCIDENTTIME, ACCIDENT_TYPE, Accident Type Desc, DAY_OF_WEEK, Day Week Description, DCA_CODE, DCA Description, DIRECTORY, EDITION, PAGE, GRID_REFERENCE_X, GRID_REFERENCE_Y, LIGHT_CONDITION, Light Condition Desc, NODE_ID, NO_OF_VEHICLES, NO_PERSONS, NO_PERSONS_INJ_2, NO_PERSONS_INJ_3, NO_PERSONS_KILLED, NO_PERSONS_NOT_INJ, POLICE_ATTEND, ROAD_GEOMETRY, Road Geometry Desc, SEVERITY, SPEED_ZONE, correct_dayofweek]
Index: []

[0 rows x 29 columns]

### Updating the data on Monday

In [48]:
# check the incorrect data on monday
acc_df[(acc_df["DAY_OF_WEEK"] == 2) & (acc_df["Day Week Description"] != "Monday") & 
       (acc_df["Day Week Description"] == acc_df["correct_dayofweek"])]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
367    T20140000882   2014-01-14     17.30.00              4   
679    T20140001548   2014-01-21     17.00.00              1   
812    T20140001812   2014-01-28     07.55.00              1   
813    T20140001815   2014-01-28     07.30.00              1   
817    T20140001821   2014-01-28     08.25.00              1   
...             ...          ...          ...            ...   
54078  T20170024697   2017-12-26     18.21.00              1   
54082  T20170024707   2017-11-28     08.00.00              1   
54246  T20180001904   2017-12-12     07.20.00              6   
54254  T20180002725   2016-08-30     08.20.00              2   
54255  T20180002839   2017-08-29     09.10.00              1   

                      Accident Type Desc  DAY_OF_WEEK Day Week Description  \
367        Collision with a fixed object            2              Tuesday   
679               Collision with vehicle            2              Tuesday   
812               Collision with vehicle            2              Tuesday   
813               Collision with vehicle            2              Tuesday   
817               Collision with vehicle            2              Tuesday   
...                                  ...          ...                  ...   
54078             Collision with vehicle            2              Tuesday   
54082             Collision with vehicle            2              Tuesday   
54246  Vehicle overturned (no collision)            2              Tuesday   
54254                  Struck Pedestrian            2              Tuesday   
54255             Collision with vehicle            2              Tuesday   

       DCA_CODE                                    DCA Description DIRECTORY  \
367         183  OFF LEFT BEND INTO OBJECT/PARKED VEHICLE      ...       VCS   
679         130     REAR END(VEHICLES IN SAME LANE)                      MEL   
812         132               RIGHT REAR.                                MEL   
813         121              RIGHT THROUGH                               MEL   
817         130     REAR END(VEHICLES IN SAME LANE)                      MEL   
...         ...                                                ...       ...   
54078       121              RIGHT THROUGH                               VCS   
54082       130     REAR END(VEHICLES IN SAME LANE)                      MEL   
54246       174  OUT OF CONTROL ON CARRIAGEWAY (ON STRAIGHT)   ...       MEL   
54254       100  PED NEAR SIDE. PED HIT BY VEHICLE FROM THE RIG...       MEL   
54255       148    VEHICLE OFF FOOTPATH STRIKES VEH ON CARRIAGEWAY       MEL   

       ... NO_PERSONS_INJ_2 NO_PERSONS_INJ_3 NO_PERSONS_KILLED  \
367    ...                0                1                 0   
679    ...                0                1                 0   
812    ...                0                1                 0   
813    ...                0                1                 0   
817    ...                0                2                 0   
...    ...              ...              ...               ...   
54078  ...                0                1                 0   
54082  ...                0                1                 0   
54246  ...                0                1                 0   
54254  ...                0                1                 0   
54255  ...                0                1                 0   

      NO_PERSONS_NOT_INJ  POLICE_ATTEND ROAD_GEOMETRY     Road Geometry Desc  \
367                    0              1             5    Not at intersection   
679                    1              2             5    Not at intersection   
812                    1              1             2         T intersection   
813                    1              1             4  Multiple intersection   
817                    1              1             5    Not at intersection   
...                  ...            ...           ...               

In [49]:
# update the data on from 2 to 3 (day_of_week)
acc_df.loc[(acc_df["DAY_OF_WEEK"] == 2) & (acc_df["Day Week Description"] != "Monday") & 
           (acc_df["Day Week Description"] == acc_df["correct_dayofweek"]), "DAY_OF_WEEK"]  = 3

In [50]:
# double-check after updating the data
acc_df[(acc_df["DAY_OF_WEEK"] == 2) & (acc_df["Day Week Description"] != "Monday") & 
       (acc_df["Day Week Description"] == acc_df["correct_dayofweek"])]

Empty DataFrame
Columns: [ACCIDENT_NO, ACCIDENTDATE, ACCIDENTTIME, ACCIDENT_TYPE, Accident Type Desc, DAY_OF_WEEK, Day Week Description, DCA_CODE, DCA Description, DIRECTORY, EDITION, PAGE, GRID_REFERENCE_X, GRID_REFERENCE_Y, LIGHT_CONDITION, Light Condition Desc, NODE_ID, NO_OF_VEHICLES, NO_PERSONS, NO_PERSONS_INJ_2, NO_PERSONS_INJ_3, NO_PERSONS_KILLED, NO_PERSONS_NOT_INJ, POLICE_ATTEND, ROAD_GEOMETRY, Road Geometry Desc, SEVERITY, SPEED_ZONE, correct_dayofweek]
Index: []

[0 rows x 29 columns]

#### On the Day Week Description perspective

In [51]:
# check the incorrect data on monday
acc_df[(acc_df["DAY_OF_WEEK"] == 2) & (acc_df["correct_dayofweek"] == "Monday") 
       & (acc_df["Day Week Description"] != "Monday")]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
3566   T20140007246   2014-08-04     13.23.00              1   
3582   T20140007274   2014-08-04     17.00.00              1   
3694   T20140007480   2014-08-04     14.30.00              1   
3884   T20140007852   2014-08-04     16.30.00              1   
4257   T20140008619   2014-08-04     11.45.00              1   
6044   T20140011948   2014-10-06     08.00.00              1   
6045   T20140011950   2014-10-06     07.00.00              1   
8460   T20140016700   2014-12-08     14.15.00              1   
14043  T20150000299   2015-06-01     10.55.00              1   
14046  T20150000304   2015-06-01     09.30.00              1   
14047  T20150000306   2015-06-01     13.15.00              6   
14053  T20150000314   2015-06-01     10.40.00              1   
14066  T20150000340   2015-06-01     18.15.00              1   
15143  T20150002350   2015-03-02     15.10.00              1   
15150  T20150002358   2015-03-02     15.50.00              1   
15151  T20150002359   2014-10-06     03.00.00              4   
15164  T20150002377   2015-03-02     18.00.00              1   
15167  T20150002380   2015-03-02     16.30.00              1   
15170  T20150002385   2015-03-02     19.00.00              1   
15735  T20150003441   2015-06-01     17.19.00              1   
16033  T20150004042   2015-06-01     14.00.00              1   
16994  T20150005835   2015-06-01     17.00.00              6   
26946  T20150024832   2015-01-12     12.00.00              2   
26950  T20150024840   2015-01-12     10.40.00              1   
26952  T20150024844   2015-01-12     13.00.00              1   
26963  T20150024862   2015-01-12     16.18.00              1   
26965  T20150024866   2015-01-12     15.45.00              1   
26966  T20150024867   2015-01-12     16.15.00              1   
26967  T20150024868   2015-01-12     17.50.00              6   
26971  T20150024874   2015-01-12     17.55.00              1   
26974  T20150024878   2015-01-12     18.30.00              1   
26979  T20150024891   2015-01-12     00.35.00              2   
28649  T20160000692   2015-01-12     10.00.00              1   
37007  T20160016872   2016-02-08     09.18.00              1   
37008  T20160016873   2016-02-08     09.05.00              4   
37013  T20160016884   2016-02-08     16.43.00              1   
37018  T20160016893   2016-02-08     16.50.00              1   
37020  T20160016899   2016-02-08     13.45.00              2   
37022  T20160016902   2016-02-08     19.00.00              1   
37072  T20160016996   2016-02-08     10.21.00              1   
37079  T20160017006   2016-02-08     10.30.00              1   
40383  T20160023616   2016-01-11     11.18.00              1   
40385  T20160023621   2016-01-11     11.31.00              1   
40389  T20160023625   2016-01-11     12.30.00              4   
40395  T20160023640   2016-01-11     11.45.00              1   
40396  T20160023641   2016-01-11     16.20.00              1   
40401  T20160023651   2016-01-11     21.10.00              1   
40406  T20160023668   2016-01-11     13.00.00              8   
40417  T20160023685   2016-01-11     12.15.00              8   
40443  T20160023738   2016-01-11     12.00.00              8   
42671  T20160028130   2016-01-11     14.15.00              1   
44939  T20170004621   2017-07-03     08.37.00              1   
44948  T20170004642   2017-07-03     08.15.00              2   
44950  T20170004651   2017-07-03     12.15.00              1   
44953  T20170004655   2017-07-03     16.25.00              4   
44957  T20170004660   2017-07-03     18.40.00              2   

                      Accident Type Desc  DAY_OF_WEEK Day Week Description  \
3566              Collision with vehicle            2              Tuesday   
3582              Collision with vehicle            2              Tuesday   
3694              Collision with vehicle            2              Tuesday   
3884              Collision with vehicle       

In [52]:
# update the data on from tuesday to monday (Day Week Description)
acc_df.loc[(acc_df["DAY_OF_WEEK"] == 2) & (acc_df["correct_dayofweek"] == "Monday") 
           & (acc_df["Day Week Description"] != "Monday"), "Day Week Description"]  = "Monday"

In [53]:
# double-check after updating the data
acc_df[(acc_df["DAY_OF_WEEK"] == 2) & (acc_df["correct_dayofweek"] == "Monday") 
       & (acc_df["Day Week Description"] != "Monday")]

Empty DataFrame
Columns: [ACCIDENT_NO, ACCIDENTDATE, ACCIDENTTIME, ACCIDENT_TYPE, Accident Type Desc, DAY_OF_WEEK, Day Week Description, DCA_CODE, DCA Description, DIRECTORY, EDITION, PAGE, GRID_REFERENCE_X, GRID_REFERENCE_Y, LIGHT_CONDITION, Light Condition Desc, NODE_ID, NO_OF_VEHICLES, NO_PERSONS, NO_PERSONS_INJ_2, NO_PERSONS_INJ_3, NO_PERSONS_KILLED, NO_PERSONS_NOT_INJ, POLICE_ATTEND, ROAD_GEOMETRY, Road Geometry Desc, SEVERITY, SPEED_ZONE, correct_dayofweek]
Index: []

[0 rows x 29 columns]

### Updating the data on Tuesday

In [54]:
# check the incorrect data on tuesday
acc_df[(acc_df["DAY_OF_WEEK"] == 3) & (acc_df["Day Week Description"] != "Tuesday") & 
       (acc_df["Day Week Description"] == acc_df["correct_dayofweek"])]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
387    T20140000924   2014-01-15     11.50.00              4   
399    T20140000961   2014-01-15     21.45.00              1   
610    T20140001420   2014-01-22     17.15.00              1   
1598   T20140003320   2014-01-15     15.30.00              1   
1857   T20140003862   2014-02-19     15.30.00              1   
...             ...          ...          ...            ...   
54111  T20170024781   2017-12-13     14.00.00              1   
54194  T20180000076   2017-01-11     14.30.00              1   
54203  T20180000257   2017-12-27     13.05.00              1   
54213  T20180000460   2017-12-27     17.15.00              1   
54217  T20180000515   2017-12-27     15.30.00              1   

                  Accident Type Desc  DAY_OF_WEEK Day Week Description  \
387    Collision with a fixed object            3            Wednesday   
399           Collision with vehicle            3            Wednesday   
610           Collision with vehicle            3            Wednesday   
1598          Collision with vehicle            3            Wednesday   
1857          Collision with vehicle            3            Wednesday   
...                              ...          ...                  ...   
54111         Collision with vehicle            3            Wednesday   
54194         Collision with vehicle            3            Wednesday   
54203         Collision with vehicle            3            Wednesday   
54213         Collision with vehicle            3            Wednesday   
54217         Collision with vehicle            3            Wednesday   

       DCA_CODE                                    DCA Description DIRECTORY  \
387         173  RIGHT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHIC...       MEL   
399         121              RIGHT THROUGH                               MEL   
610         137           LEFT TURN SIDESWIPE                            MEL   
1598        130     REAR END(VEHICLES IN SAME LANE)                      MEL   
1857        137           LEFT TURN SIDESWIPE                            MEL   
...         ...                                                ...       ...   
54111       120         HEAD ON (NOT OVERTAKING)                         VCS   
54194       130     REAR END(VEHICLES IN SAME LANE)                      MEL   
54203       110    CROSS TRAFFIC(INTERSECTIONS ONLY)                     VCS   
54213       140                  U TURN                                  MEL   
54217       130     REAR END(VEHICLES IN SAME LANE)                      MEL   

       ... NO_PERSONS_INJ_2 NO_PERSONS_INJ_3 NO_PERSONS_KILLED  \
387    ...                0                1                 0   
399    ...                0                1                 0   
610    ...                0                1                 0   
1598   ...                0                1                 0   
1857   ...                0                1                 0   
...    ...              ...              ...               ...   
54111  ...                0                2                 0   
54194  ...                0                1                 0   
54203  ...                0                1                 0   
54213  ...                0                1                 0   
54217  ...                0                1                 0   

      NO_PERSONS_NOT_INJ  POLICE_ATTEND ROAD_GEOMETRY   Road Geometry Desc  \
387                    0              1             5  Not at intersection   
399                    2              1             2       T intersection   
610                    1              1             5  Not at intersection   
1598                   1              2             1   Cross intersection   
1857                   1              2             2       T intersection   
...                  ...            ...           ...                  ...   
54111                  1              1           

In [55]:
# update the data on from 3 to 4 (day_of_week)
acc_df.loc[(acc_df["DAY_OF_WEEK"] == 3) & (acc_df["Day Week Description"] != "Tuesday") & 
           (acc_df["Day Week Description"] == acc_df["correct_dayofweek"]), "DAY_OF_WEEK"]  = 4

In [56]:
# double-check after updating the data
acc_df[(acc_df["DAY_OF_WEEK"] == 3) & (acc_df["Day Week Description"] != "Tuesday") & 
       (acc_df["Day Week Description"] == acc_df["correct_dayofweek"])]

Empty DataFrame
Columns: [ACCIDENT_NO, ACCIDENTDATE, ACCIDENTTIME, ACCIDENT_TYPE, Accident Type Desc, DAY_OF_WEEK, Day Week Description, DCA_CODE, DCA Description, DIRECTORY, EDITION, PAGE, GRID_REFERENCE_X, GRID_REFERENCE_Y, LIGHT_CONDITION, Light Condition Desc, NODE_ID, NO_OF_VEHICLES, NO_PERSONS, NO_PERSONS_INJ_2, NO_PERSONS_INJ_3, NO_PERSONS_KILLED, NO_PERSONS_NOT_INJ, POLICE_ATTEND, ROAD_GEOMETRY, Road Geometry Desc, SEVERITY, SPEED_ZONE, correct_dayofweek]
Index: []

[0 rows x 29 columns]

#### On the Day Week Description perspective

In [57]:
# check the incorrect data on monday
acc_df[(acc_df["DAY_OF_WEEK"] == 3) & (acc_df["correct_dayofweek"] == "Tuesday") 
       & (acc_df["Day Week Description"] != "Tuesday")]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
3324   T20140006793   2014-02-04     08.30.00              1   
4952   T20140009897   2014-12-02     18.00.00              2   
11598  T20140022807   2014-02-04     05.15.00              4   
16625  T20150005178   2015-11-03     06.50.00              8   
16627  T20150005180   2015-11-03     09.14.00              1   
...             ...          ...          ...            ...   
44698  T20170004159   2017-01-03     09.10.00              1   
44704  T20170004168   2017-01-03     08.25.00              2   
44707  T20170004175   2017-01-03     13.30.00              1   
44717  T20170004192   2017-01-03     15.30.00              2   
47148  T20170009185   2017-01-03     14.30.00              1   

                      Accident Type Desc  DAY_OF_WEEK Day Week Description  \
3324              Collision with vehicle            3            Wednesday   
4952                   Struck Pedestrian            3            Wednesday   
11598      Collision with a fixed object            3            Wednesday   
16625  No collision and no object struck            3            Wednesday   
16627             Collision with vehicle            3            Wednesday   
...                                  ...          ...                  ...   
44698             Collision with vehicle            3            Wednesday   
44704                  Struck Pedestrian            3            Wednesday   
44707             Collision with vehicle            3            Wednesday   
44717                  Struck Pedestrian            3            Wednesday   
47148             Collision with vehicle            3            Wednesday   

       DCA_CODE                                    DCA Description DIRECTORY  \
3324        110    CROSS TRAFFIC(INTERSECTIONS ONLY)                     MEL   
4952        102  FAR SIDE. PED HIT BY VEHICLE FROM THE LEFT    ...       MEL   
11598       181  OFF RIGHT BEND INTO OBJECT/PARKED VEHICLE     ...       MEL   
16625       174  OUT OF CONTROL ON CARRIAGEWAY (ON STRAIGHT)   ...       MEL   
16627       110    CROSS TRAFFIC(INTERSECTIONS ONLY)                     VCS   
...         ...                                                ...       ...   
44698       110    CROSS TRAFFIC(INTERSECTIONS ONLY)                     MEL   
44704       100  PED NEAR SIDE. PED HIT BY VEHICLE FROM THE RIG...       MEL   
44707       110    CROSS TRAFFIC(INTERSECTIONS ONLY)                     MEL   
44717       100  PED NEAR SIDE. PED HIT BY VEHICLE FROM THE RIG...       MEL   
47148       163  VEHICLE STRIKES DOOR OF PARKED/STATIONARY VEHI...             

       ... NO_PERSONS_INJ_2 NO_PERSONS_INJ_3 NO_PERSONS_KILLED  \
3324   ...                1                0                 0   
4952   ...                0                1                 0   
11598  ...                0                1                 0   
16625  ...                1                0                 0   
16627  ...                0                1                 0   
...    ...              ...              ...               ...   
44698  ...                0                2                 0   
44704  ...                0                1                 0   
44707  ...                0                1                 0   
44717  ...                1                0                 0   
47148  ...                0                1                 0   

      NO_PERSONS_NOT_INJ  POLICE_ATTEND ROAD_GEOMETRY   Road Geometry Desc  \
3324                   1              1             1   Cross intersection   
4952                   2              2             2       T intersection   
11598                  0              2             5  Not at intersection   
16625                  1              1             2       T intersection   
16627                  1              1             1   Cross intersection   
...                  ...            ...           ...                  ...   
44

In [58]:
# update the data on from wednesday to tuesday (Day Week Description)
acc_df.loc[(acc_df["DAY_OF_WEEK"] == 3) & (acc_df["correct_dayofweek"] == "Tuesday") 
       & (acc_df["Day Week Description"] != "Tuesday"), "Day Week Description"]  = "Tuesday"

In [59]:
# double-check after updating the data
acc_df[(acc_df["DAY_OF_WEEK"] == 3) & (acc_df["correct_dayofweek"] == "Tuesday") 
       & (acc_df["Day Week Description"] != "Tuesday")]

Empty DataFrame
Columns: [ACCIDENT_NO, ACCIDENTDATE, ACCIDENTTIME, ACCIDENT_TYPE, Accident Type Desc, DAY_OF_WEEK, Day Week Description, DCA_CODE, DCA Description, DIRECTORY, EDITION, PAGE, GRID_REFERENCE_X, GRID_REFERENCE_Y, LIGHT_CONDITION, Light Condition Desc, NODE_ID, NO_OF_VEHICLES, NO_PERSONS, NO_PERSONS_INJ_2, NO_PERSONS_INJ_3, NO_PERSONS_KILLED, NO_PERSONS_NOT_INJ, POLICE_ATTEND, ROAD_GEOMETRY, Road Geometry Desc, SEVERITY, SPEED_ZONE, correct_dayofweek]
Index: []

[0 rows x 29 columns]

### Updating the data on Wednesday

In [60]:
# check the incorrect data on wednesday
acc_df[(acc_df["DAY_OF_WEEK"] == 4) & (acc_df["Day Week Description"] != "Wednesday") & 
       (acc_df["Day Week Description"] == acc_df["correct_dayofweek"])]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
417    T20140001000   2014-01-16     12.06.00              6   
420    T20140001007   2014-01-16     13.20.00              1   
433    T20140001032   2014-01-16     15.58.00              1   
553    T20140001288   2014-01-16     07.25.00              1   
615    T20140001434   2014-01-23     02.40.00              6   
...             ...          ...          ...            ...   
54128  T20170024819   2017-12-28     23.15.00              1   
54129  T20170024820   2017-12-28     15.42.00              1   
54211  T20180000427   2016-04-14     18.15.00              1   
54220  T20180000551   2017-12-28     12.10.00              1   
54229  T20180000839   2017-12-14     15.30.00              1   

                      Accident Type Desc  DAY_OF_WEEK Day Week Description  \
417    Vehicle overturned (no collision)            4             Thursday   
420               Collision with vehicle            4             Thursday   
433               Collision with vehicle            4             Thursday   
553               Collision with vehicle            4             Thursday   
615    Vehicle overturned (no collision)            4             Thursday   
...                                  ...          ...                  ...   
54128             Collision with vehicle            4             Thursday   
54129             Collision with vehicle            4             Thursday   
54211             Collision with vehicle            4             Thursday   
54220             Collision with vehicle            4             Thursday   
54229             Collision with vehicle            4             Thursday   

       DCA_CODE                                    DCA Description DIRECTORY  \
417         151       OUT OF CONTROL (OVERTAKING)                        MEL   
420         110    CROSS TRAFFIC(INTERSECTIONS ONLY)                     MEL   
433         135    LANE CHANGE LEFT (NOT OVERTAKING)                     MEL   
553         121              RIGHT THROUGH                               MEL   
615         174  OUT OF CONTROL ON CARRIAGEWAY (ON STRAIGHT)   ...       MEL   
...         ...                                                ...       ...   
54128       142             LEAVING PARKING                              MEL   
54129       121              RIGHT THROUGH                               MEL   
54211       130     REAR END(VEHICLES IN SAME LANE)                      MEL   
54220       130     REAR END(VEHICLES IN SAME LANE)                      MEL   
54229       130     REAR END(VEHICLES IN SAME LANE)                      MEL   

       ... NO_PERSONS_INJ_2 NO_PERSONS_INJ_3 NO_PERSONS_KILLED  \
417    ...                1                0                 0   
420    ...                1                0                 0   
433    ...                0                1                 0   
553    ...                0                1                 0   
615    ...                0                1                 0   
...    ...              ...              ...               ...   
54128  ...                0                1                 0   
54129  ...                0                1                 0   
54211  ...                0                1                 0   
54220  ...                0                1                 0   
54229  ...                0                1                 0   

      NO_PERSONS_NOT_INJ  POLICE_ATTEND ROAD_GEOMETRY   Road Geometry Desc  \
417                    0              1             5  Not at intersection   
420                    1              1             1   Cross intersection   
433                    2              1             5  Not at intersection   
553                    1              1             2       T intersection   
615                    0              2             2       T intersection   
...                  ...            ...           ...                  ...   
54

In [61]:
# update the data on from 4 to 5 (day_of_week)
acc_df.loc[(acc_df["DAY_OF_WEEK"] == 4) & (acc_df["Day Week Description"] != "Wednesday") & 
           (acc_df["Day Week Description"] == acc_df["correct_dayofweek"]), "DAY_OF_WEEK"]  = 5

In [62]:
# double-check after updating the data
acc_df[(acc_df["DAY_OF_WEEK"] == 4) & (acc_df["Day Week Description"] != "Wednesday") & 
       (acc_df["Day Week Description"] == acc_df["correct_dayofweek"])]

Empty DataFrame
Columns: [ACCIDENT_NO, ACCIDENTDATE, ACCIDENTTIME, ACCIDENT_TYPE, Accident Type Desc, DAY_OF_WEEK, Day Week Description, DCA_CODE, DCA Description, DIRECTORY, EDITION, PAGE, GRID_REFERENCE_X, GRID_REFERENCE_Y, LIGHT_CONDITION, Light Condition Desc, NODE_ID, NO_OF_VEHICLES, NO_PERSONS, NO_PERSONS_INJ_2, NO_PERSONS_INJ_3, NO_PERSONS_KILLED, NO_PERSONS_NOT_INJ, POLICE_ATTEND, ROAD_GEOMETRY, Road Geometry Desc, SEVERITY, SPEED_ZONE, correct_dayofweek]
Index: []

[0 rows x 29 columns]

#### On the Day Week Description perspective

In [63]:
# check the incorrect data on wednesday
acc_df[(acc_df["DAY_OF_WEEK"] == 4) & (acc_df["correct_dayofweek"] == "Wednesday") 
       & (acc_df["Day Week Description"] != "Wednesday")]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
9331   T20140018354   2014-04-09     17.15.00              4   
9334   T20140018361   2014-04-09     15.15.00              1   
9347   T20140018378   2014-04-09     20.20.00              1   
9350   T20140018384   2014-04-09     18.35.00              1   
10561  T20140020820   2014-09-10     10.30.00              1   
...             ...          ...          ...            ...   
53541  T20170023414   2017-07-12     21.34.00              1   
53613  T20170023574   2017-07-12     19.45.00              2   
53645  T20170023644   2017-07-12     16.20.00              1   
53680  T20170023717   2017-07-12     08.20.00              1   
54219  T20180000544   2017-07-12     10.00.00              2   

                  Accident Type Desc  DAY_OF_WEEK Day Week Description  \
9331   Collision with a fixed object            4             Thursday   
9334          Collision with vehicle            4             Thursday   
9347          Collision with vehicle            4             Thursday   
9350          Collision with vehicle            4             Thursday   
10561         Collision with vehicle            4             Thursday   
...                              ...          ...                  ...   
53541         Collision with vehicle            4             Thursday   
53613              Struck Pedestrian            4             Thursday   
53645         Collision with vehicle            4             Thursday   
53680         Collision with vehicle            4             Thursday   
54219              Struck Pedestrian            4             Thursday   

       DCA_CODE                                    DCA Description DIRECTORY  \
9331        171  LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICL...       MEL   
9334        110    CROSS TRAFFIC(INTERSECTIONS ONLY)                     MEL   
9347        121              RIGHT THROUGH                               MEL   
9350        130     REAR END(VEHICLES IN SAME LANE)                      MEL   
10561       130     REAR END(VEHICLES IN SAME LANE)                      MEL   
...         ...                                                ...       ...   
53541       110    CROSS TRAFFIC(INTERSECTIONS ONLY)                     MEL   
53613       100  PED NEAR SIDE. PED HIT BY VEHICLE FROM THE RIG...       MEL   
53645       130     REAR END(VEHICLES IN SAME LANE)                      MEL   
53680       130     REAR END(VEHICLES IN SAME LANE)                      MEL   
54219       109  ANY MANOEUVRE INVOLVING PED NOT INCLUDED IN DC...       VCS   

       ... NO_PERSONS_INJ_2 NO_PERSONS_INJ_3 NO_PERSONS_KILLED  \
9331   ...                1                0                 0   
9334   ...                0                1                 0   
9347   ...                0                1                 0   
9350   ...                0                1                 0   
10561  ...                0                1                 0   
...    ...              ...              ...               ...   
53541  ...                0                1                 0   
53613  ...                0                1                 0   
53645  ...                0                1                 0   
53680  ...                0                1                 0   
54219  ...                0                1                 0   

      NO_PERSONS_NOT_INJ  POLICE_ATTEND ROAD_GEOMETRY   Road Geometry Desc  \
9331                   0              1             5  Not at intersection   
9334                   1              1             1   Cross intersection   
9347                   1              1             1   Cross intersection   
9350                   1              1             5  Not at intersection   
10561                  2              1             1   Cross intersection   
...                  ...            ...           ...                  ...   
53541                  1              1           

In [64]:
# update the data on from thursday to wednesday (Day Week Description)
acc_df.loc[(acc_df["DAY_OF_WEEK"] == 4) & (acc_df["correct_dayofweek"] == "Wednesday") 
           & (acc_df["Day Week Description"] != "Wednesday"), "Day Week Description"]  = "Wednesday"

In [65]:
# double-check after updating the data
acc_df[(acc_df["DAY_OF_WEEK"] == 4) & (acc_df["correct_dayofweek"] == "Wednesday") 
       & (acc_df["Day Week Description"] != "Wednesday")]

Empty DataFrame
Columns: [ACCIDENT_NO, ACCIDENTDATE, ACCIDENTTIME, ACCIDENT_TYPE, Accident Type Desc, DAY_OF_WEEK, Day Week Description, DCA_CODE, DCA Description, DIRECTORY, EDITION, PAGE, GRID_REFERENCE_X, GRID_REFERENCE_Y, LIGHT_CONDITION, Light Condition Desc, NODE_ID, NO_OF_VEHICLES, NO_PERSONS, NO_PERSONS_INJ_2, NO_PERSONS_INJ_3, NO_PERSONS_KILLED, NO_PERSONS_NOT_INJ, POLICE_ATTEND, ROAD_GEOMETRY, Road Geometry Desc, SEVERITY, SPEED_ZONE, correct_dayofweek]
Index: []

[0 rows x 29 columns]

### Updating the data on Thursday

In [66]:
# check the incorrect data on thursday
acc_df[(acc_df["DAY_OF_WEEK"] == 5) & (acc_df["Day Week Description"] != "Thursday") & 
       (acc_df["Day Week Description"] == acc_df["correct_dayofweek"])]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
1074   T20140002313   2014-01-24     19.30.00              8   
1480   T20140003091   2014-02-14     06.10.00              1   
2013   T20140004176   2014-02-28     09.34.00              2   
2221   T20140004599   2014-02-28     21.30.00              1   
2497   T20140005160   2014-01-31     17.40.00              1   
...             ...          ...          ...            ...   
54156  T20170024880   2017-12-29     18.50.00              1   
54160  T20170024902   2017-12-29     11.30.00              1   
54161  T20170024904   2017-12-29     20.13.00              4   
54167  T20170024914   2017-12-29     09.40.00              1   
54202  T20180000216   2017-12-29     15.00.00              1   

                      Accident Type Desc  DAY_OF_WEEK Day Week Description  \
1074   No collision and no object struck            5               Friday   
1480              Collision with vehicle            5               Friday   
2013                   Struck Pedestrian            5               Friday   
2221              Collision with vehicle            5               Friday   
2497              Collision with vehicle            5               Friday   
...                                  ...          ...                  ...   
54156             Collision with vehicle            5               Friday   
54160             Collision with vehicle            5               Friday   
54161      Collision with a fixed object            5               Friday   
54167             Collision with vehicle            5               Friday   
54202             Collision with vehicle            5               Friday   

       DCA_CODE                                    DCA Description DIRECTORY  \
1074        174  OUT OF CONTROL ON CARRIAGEWAY (ON STRAIGHT)   ...       VCS   
1480        113     RIGHT NEAR (INTERSECTIONS ONLY)                      MEL   
2013        102  FAR SIDE. PED HIT BY VEHICLE FROM THE LEFT    ...       MEL   
2221        130     REAR END(VEHICLES IN SAME LANE)                      MEL   
2497        130     REAR END(VEHICLES IN SAME LANE)                      MEL   
...         ...                                                ...       ...   
54156       120         HEAD ON (NOT OVERTAKING)                         MEL   
54160       110    CROSS TRAFFIC(INTERSECTIONS ONLY)                     MEL   
54161       173  RIGHT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHIC...       MEL   
54167       110    CROSS TRAFFIC(INTERSECTIONS ONLY)                     VCS   
54202       130     REAR END(VEHICLES IN SAME LANE)                      MEL   

       ... NO_PERSONS_INJ_2 NO_PERSONS_INJ_3 NO_PERSONS_KILLED  \
1074   ...                1                0                 0   
1480   ...                0                1                 0   
2013   ...                0                1                 0   
2221   ...                0                1                 0   
2497   ...                0                1                 0   
...    ...              ...              ...               ...   
54156  ...                0                1                 0   
54160  ...                0                1                 0   
54161  ...                0                1                 0   
54167  ...                0                1                 0   
54202  ...                0                1                 0   

      NO_PERSONS_NOT_INJ  POLICE_ATTEND ROAD_GEOMETRY   Road Geometry Desc  \
1074                   0              2             5  Not at intersection   
1480                   1              2             1   Cross intersection   
2013                   1              1             2       T intersection   
2221                   1              2             5  Not at intersection   
2497                   1              2             1   Cross intersection   
...                  ...            ...           ...                  ...   
54

In [67]:
# update the data on from 5 to 6 (day_of_week)
acc_df.loc[(acc_df["DAY_OF_WEEK"] == 5) & (acc_df["Day Week Description"] != "Thursday") & 
           (acc_df["Day Week Description"] == acc_df["correct_dayofweek"]), "DAY_OF_WEEK"]  = 6

In [68]:
# double-check after updating the data
acc_df[(acc_df["DAY_OF_WEEK"] == 5) & (acc_df["Day Week Description"] != "Thursday") & 
       (acc_df["Day Week Description"] == acc_df["correct_dayofweek"])]

Empty DataFrame
Columns: [ACCIDENT_NO, ACCIDENTDATE, ACCIDENTTIME, ACCIDENT_TYPE, Accident Type Desc, DAY_OF_WEEK, Day Week Description, DCA_CODE, DCA Description, DIRECTORY, EDITION, PAGE, GRID_REFERENCE_X, GRID_REFERENCE_Y, LIGHT_CONDITION, Light Condition Desc, NODE_ID, NO_OF_VEHICLES, NO_PERSONS, NO_PERSONS_INJ_2, NO_PERSONS_INJ_3, NO_PERSONS_KILLED, NO_PERSONS_NOT_INJ, POLICE_ATTEND, ROAD_GEOMETRY, Road Geometry Desc, SEVERITY, SPEED_ZONE, correct_dayofweek]
Index: []

[0 rows x 29 columns]

#### On the Day Week Description perspective

In [69]:
# check the incorrect data on thursday
acc_df[(acc_df["DAY_OF_WEEK"] == 5) & (acc_df["correct_dayofweek"] == "Thursday") 
       & (acc_df["Day Week Description"] != "Thursday")]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
2298   T20140004742   2014-07-03     06.40.00              1   
2303   T20140004750   2014-07-03     13.10.00              1   
23571  T20150018387   2015-04-09     10.45.00              1   
23581  T20150018400   2015-04-09     12.10.00              1   
23596  T20150018427   2015-04-09     15.40.00              2   
...             ...          ...          ...            ...   
53360  T20170023015   2017-01-12     15.30.00              1   
53365  T20170023027   2017-01-12     20.00.00              1   
53475  T20170023264   2017-01-12     11.00.00              1   
53546  T20170023425   2017-01-12     09.00.00              1   
53548  T20170023432   2017-01-12     15.40.00              2   

           Accident Type Desc  DAY_OF_WEEK Day Week Description  DCA_CODE  \
2298   Collision with vehicle            5               Friday       130   
2303   Collision with vehicle            5               Friday       130   
23571  Collision with vehicle            5               Friday       110   
23581  Collision with vehicle            5               Friday       121   
23596       Struck Pedestrian            5               Friday       101   
...                       ...          ...                  ...       ...   
53360  Collision with vehicle            5               Friday       169   
53365  Collision with vehicle            5               Friday       112   
53475  Collision with vehicle            5               Friday       120   
53546  Collision with vehicle            5               Friday       130   
53548       Struck Pedestrian            5               Friday       102   

                                         DCA Description DIRECTORY  ...  \
2298      REAR END(VEHICLES IN SAME LANE)                      MEL  ...   
2303      REAR END(VEHICLES IN SAME LANE)                      MEL  ...   
23571    CROSS TRAFFIC(INTERSECTIONS ONLY)                     VCS  ...   
23581              RIGHT THROUGH                               MEL  ...   
23596  PED EMERGES FROM IN FRONT OF PARKED OR STATION...       MEL  ...   
...                                                  ...       ...  ...   
53360              OTHER ON PATH                               MEL  ...   
53365      LEFT FAR (INTERSECTIONS ONLY)                       MEL  ...   
53475         HEAD ON (NOT OVERTAKING)                         MEL  ...   
53546     REAR END(VEHICLES IN SAME LANE)                      MEL  ...   
53548  FAR SIDE. PED HIT BY VEHICLE FROM THE LEFT    ...       MEL  ...   

      NO_PERSONS_INJ_2 NO_PERSONS_INJ_3 NO_PERSONS_KILLED NO_PERSONS_NOT_INJ  \
2298                 0                2                 0                  4   
2303                 2                0                 0                  2   
23571                0                1                 0                  4   
23581                1                0                 0                  1   
23596                0                1                 0                  1   
...                ...              ...               ...                ...   
53360                1                0                 0                  0   
53365                0                2                 0                  0   
53475                1                1                 0                  1   
53546                0                1                 0                  1   
53548                0                1                 0                  1   

       POLICE_ATTEND ROAD_GEOMETRY   Road Geometry Desc  SEVERITY  SPEED_ZONE  \
2298               1             2       T intersection         3          60   
2303               1             1   Cross intersection         2          80   
23571              1             1   Cross intersection         3          60   
23581              1             5  Not at intersection         2          60   
23596              1             5  Not at inte

In [70]:
# update the data on from friday to thursday (Day Week Description)
acc_df.loc[(acc_df["DAY_OF_WEEK"] == 5) & (acc_df["correct_dayofweek"] == "Thursday") 
           & (acc_df["Day Week Description"] != "Thursday"), "Day Week Description"]  = "Thursday"

In [71]:
# double-check after updating the data
acc_df[(acc_df["DAY_OF_WEEK"] == 5) & (acc_df["correct_dayofweek"] == "Thursday") 
       & (acc_df["Day Week Description"] != "Thursday")]

Empty DataFrame
Columns: [ACCIDENT_NO, ACCIDENTDATE, ACCIDENTTIME, ACCIDENT_TYPE, Accident Type Desc, DAY_OF_WEEK, Day Week Description, DCA_CODE, DCA Description, DIRECTORY, EDITION, PAGE, GRID_REFERENCE_X, GRID_REFERENCE_Y, LIGHT_CONDITION, Light Condition Desc, NODE_ID, NO_OF_VEHICLES, NO_PERSONS, NO_PERSONS_INJ_2, NO_PERSONS_INJ_3, NO_PERSONS_KILLED, NO_PERSONS_NOT_INJ, POLICE_ATTEND, ROAD_GEOMETRY, Road Geometry Desc, SEVERITY, SPEED_ZONE, correct_dayofweek]
Index: []

[0 rows x 29 columns]

### Updating the data on Friday

In [72]:
# check the incorrect data on friday
acc_df[(acc_df["DAY_OF_WEEK"] == 6) & (acc_df["Day Week Description"] != "Friday") & 
       (acc_df["Day Week Description"] == acc_df["correct_dayofweek"])]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
277    T20140000693   2014-11-01     16.30.00              2   
571    T20140001332   2014-01-18     23.15.00              7   
826    T20140001839   2014-01-25     15.30.00              8   
1146   T20140002446   2014-01-18     15.30.00              6   
1172   T20140002494   2014-01-25     11.45.00              1   
...             ...          ...          ...            ...   
54198  T20180000103   2017-12-23     10.10.00              1   
54225  T20180000659   2017-12-23     16.24.00              4   
54226  T20180000665   2017-12-30     10.00.00              4   
54251  T20180002565   2017-10-14     17.00.00              8   
54253  T20180002575   2017-12-23     12.00.00              1   

                      Accident Type Desc  DAY_OF_WEEK Day Week Description  \
277                    Struck Pedestrian            6             Saturday   
571       Fall from or in moving vehicle            6             Saturday   
826    No collision and no object struck            6             Saturday   
1146   Vehicle overturned (no collision)            6             Saturday   
1172              Collision with vehicle            6             Saturday   
...                                  ...          ...                  ...   
54198             Collision with vehicle            6             Saturday   
54225      Collision with a fixed object            6             Saturday   
54226      Collision with a fixed object            6             Saturday   
54251  No collision and no object struck            6             Saturday   
54253             Collision with vehicle            6             Saturday   

       DCA_CODE                                    DCA Description DIRECTORY  \
277         101  PED EMERGES FROM IN FRONT OF PARKED OR STATION...       MEL   
571         190           FELL IN/FROM VEHICLE                           MEL   
826         184  OUT OF CONTROL ON CARRIAGEWAY (ON BEND)       ...       VCS   
1146        174  OUT OF CONTROL ON CARRIAGEWAY (ON STRAIGHT)   ...       MEL   
1172        130     REAR END(VEHICLES IN SAME LANE)                      MEL   
...         ...                                                ...       ...   
54198       163  VEHICLE STRIKES DOOR OF PARKED/STATIONARY VEHI...       MEL   
54225       171  LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICL...       MEL   
54226       173  RIGHT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHIC...       NaN   
54251       174  OUT OF CONTROL ON CARRIAGEWAY (ON STRAIGHT)   ...       MEL   
54253       130     REAR END(VEHICLES IN SAME LANE)                      MEL   

       ... NO_PERSONS_INJ_2 NO_PERSONS_INJ_3 NO_PERSONS_KILLED  \
277    ...                0                1                 0   
571    ...                1                0                 0   
826    ...                1                0                 0   
1146   ...                0                1                 0   
1172   ...                0                1                 0   
...    ...              ...              ...               ...   
54198  ...                0                1                 0   
54225  ...                0                1                 0   
54226  ...                0                1                 0   
54251  ...                0                2                 0   
54253  ...                0                2                 0   

      NO_PERSONS_NOT_INJ  POLICE_ATTEND ROAD_GEOMETRY     Road Geometry Desc  \
277                    1              2             3         Y intersection   
571                    3              2             5    Not at intersection   
826                    0              2             5    Not at intersection   
1146                   0              2             4  Multiple intersection   
1172                   2              2             1     Cross intersection   
...                  ...            ...           ...               

In [73]:
# update the data on from 6 to 7 (day_of_week)
acc_df.loc[(acc_df["DAY_OF_WEEK"] == 6) & (acc_df["Day Week Description"] != "Friday") & 
           (acc_df["Day Week Description"] == acc_df["correct_dayofweek"]), "DAY_OF_WEEK"]  = 7

In [74]:
# double-check after updating the data
acc_df[(acc_df["DAY_OF_WEEK"] == 6) & (acc_df["Day Week Description"] != "Friday") & 
       (acc_df["Day Week Description"] == acc_df["correct_dayofweek"])]

Empty DataFrame
Columns: [ACCIDENT_NO, ACCIDENTDATE, ACCIDENTTIME, ACCIDENT_TYPE, Accident Type Desc, DAY_OF_WEEK, Day Week Description, DCA_CODE, DCA Description, DIRECTORY, EDITION, PAGE, GRID_REFERENCE_X, GRID_REFERENCE_Y, LIGHT_CONDITION, Light Condition Desc, NODE_ID, NO_OF_VEHICLES, NO_PERSONS, NO_PERSONS_INJ_2, NO_PERSONS_INJ_3, NO_PERSONS_KILLED, NO_PERSONS_NOT_INJ, POLICE_ATTEND, ROAD_GEOMETRY, Road Geometry Desc, SEVERITY, SPEED_ZONE, correct_dayofweek]
Index: []

[0 rows x 29 columns]

#### On the Day Week Description perspective

In [75]:
# check the incorrect data on friday
acc_df[(acc_df["DAY_OF_WEEK"] == 6) & (acc_df["correct_dayofweek"] == "Friday") 
       & (acc_df["Day Week Description"] != "Friday")]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
2042   T20140004245   2014-01-03     00.50.00              1   
2067   T20140004293   2014-01-03     15.45.00              4   
2080   T20140004323   2014-01-03     20.25.00              1   
2088   T20140004344   2014-01-03     18.30.00              1   
2536   T20140005233   2014-01-03     17.20.00              1   
16497  T20150004904   2015-07-03     07.00.00              1   
16502  T20150004914   2015-07-03     11.15.00              3   
16513  T20150004937   2015-07-03     17.30.00              4   
16517  T20150004945   2015-07-03     19.39.00              4   
16519  T20150004949   2015-07-03     20.30.00              6   
16532  T20150004978   2015-07-03     07.30.00              1   
45097  T20170004954   2017-11-03     13.10.00              1   
45099  T20170004960   2017-11-03     16.25.00              1   
45110  T20170004987   2017-11-03     21.50.00              1   
45359  T20170005478   2017-11-03     11.30.00              8   
45915  T20170006659   2017-11-03     16.15.00              1   
46107  T20170007045   2017-08-04     01.20.00              4   
46117  T20170007071   2017-08-04     12.50.00              4   
46120  T20170007076   2017-08-04     13.30.00              1   
46132  T20170007099   2017-08-04     19.55.00              1   
46437  T20170007710   2017-08-04     13.45.00              1   
48180  T20170011364   2017-10-06     10.21.00              1   
48189  T20170011383   2017-10-06     13.15.00              2   
48190  T20170011384   2017-10-06     16.05.00              1   
48191  T20170011385   2017-10-06     13.05.00              1   
48194  T20170011396   2017-10-06     19.15.00              1   
48214  T20170011435   2017-10-06     12.00.00              7   
48237  T20170011494   2017-10-06     13.37.00              1   
48252  T20170011519   2017-10-06     13.40.00              1   
48276  T20170011576   2017-10-06     17.00.00              1   
48375  T20170011808   2017-10-06     12.30.00              1   
48479  T20170012034   2017-10-06     14.00.00              4   
48768  T20170012676   2017-10-06     09.50.00              2   
48807  T20170012752   2017-10-06     06.30.00              3   
50067  T20170015585   2017-12-08     02.55.00              4   
50070  T20170015589   2017-12-08     09.00.00              6   
50071  T20170015590   2017-12-08     07.15.00              4   
50079  T20170015622   2017-12-08     19.15.00              1   
50082  T20170015626   2017-12-08     20.40.00              1   
50083  T20170015627   2017-12-08     20.40.00              2   
50084  T20170015632   2017-12-08     16.30.00              1   
50086  T20170015649   2017-12-08     07.55.00              1   
51757  T20170019509   2017-10-06     13.15.00              1   

                      Accident Type Desc  DAY_OF_WEEK Day Week Description  \
2042              Collision with vehicle            6             Saturday   
2067       Collision with a fixed object            6             Saturday   
2080              Collision with vehicle            6             Saturday   
2088              Collision with vehicle            6             Saturday   
2536              Collision with vehicle            6             Saturday   
16497             Collision with vehicle            6             Saturday   
16502                      Struck animal            6             Saturday   
16513      Collision with a fixed object            6             Saturday   
16517      Collision with a fixed object            6             Saturday   
16519  Vehicle overturned (no collision)            6             Saturday   
16532             Collision with vehicle            6             Saturday   
45097             Collision with vehicle            6             Saturday   
45099             Collision with vehicle            6             Saturday   
45110             Collision with vehicle            6             Saturday   
45359  No collision a

In [76]:
# update the data on from saturday to friday (Day Week Description)
acc_df.loc[(acc_df["DAY_OF_WEEK"] == 6) & (acc_df["correct_dayofweek"] == "Friday") 
           & (acc_df["Day Week Description"] != "Friday"), "Day Week Description"]  = "Friday"

In [77]:
# double-check after updating the data
acc_df[(acc_df["DAY_OF_WEEK"] == 6) & (acc_df["correct_dayofweek"] == "Friday") 
       & (acc_df["Day Week Description"] != "Friday")]

Empty DataFrame
Columns: [ACCIDENT_NO, ACCIDENTDATE, ACCIDENTTIME, ACCIDENT_TYPE, Accident Type Desc, DAY_OF_WEEK, Day Week Description, DCA_CODE, DCA Description, DIRECTORY, EDITION, PAGE, GRID_REFERENCE_X, GRID_REFERENCE_Y, LIGHT_CONDITION, Light Condition Desc, NODE_ID, NO_OF_VEHICLES, NO_PERSONS, NO_PERSONS_INJ_2, NO_PERSONS_INJ_3, NO_PERSONS_KILLED, NO_PERSONS_NOT_INJ, POLICE_ATTEND, ROAD_GEOMETRY, Road Geometry Desc, SEVERITY, SPEED_ZONE, correct_dayofweek]
Index: []

[0 rows x 29 columns]

### Updating the data on Saturday

In [78]:
# check the incorrect data on saturday
acc_df[(acc_df["DAY_OF_WEEK"] == 7) & (acc_df["Day Week Description"] != "Saturday") & 
       (acc_df["Day Week Description"] == acc_df["correct_dayofweek"])]

Empty DataFrame
Columns: [ACCIDENT_NO, ACCIDENTDATE, ACCIDENTTIME, ACCIDENT_TYPE, Accident Type Desc, DAY_OF_WEEK, Day Week Description, DCA_CODE, DCA Description, DIRECTORY, EDITION, PAGE, GRID_REFERENCE_X, GRID_REFERENCE_Y, LIGHT_CONDITION, Light Condition Desc, NODE_ID, NO_OF_VEHICLES, NO_PERSONS, NO_PERSONS_INJ_2, NO_PERSONS_INJ_3, NO_PERSONS_KILLED, NO_PERSONS_NOT_INJ, POLICE_ATTEND, ROAD_GEOMETRY, Road Geometry Desc, SEVERITY, SPEED_ZONE, correct_dayofweek]
Index: []

[0 rows x 29 columns]

#### On the Day Week Description perspective

In [79]:
# check the incorrect data on saturday
acc_df[(acc_df["DAY_OF_WEEK"] == 7) & (acc_df["correct_dayofweek"] == "Saturday") 
       & (acc_df["Day Week Description"] != "Saturday")]

Empty DataFrame
Columns: [ACCIDENT_NO, ACCIDENTDATE, ACCIDENTTIME, ACCIDENT_TYPE, Accident Type Desc, DAY_OF_WEEK, Day Week Description, DCA_CODE, DCA Description, DIRECTORY, EDITION, PAGE, GRID_REFERENCE_X, GRID_REFERENCE_Y, LIGHT_CONDITION, Light Condition Desc, NODE_ID, NO_OF_VEHICLES, NO_PERSONS, NO_PERSONS_INJ_2, NO_PERSONS_INJ_3, NO_PERSONS_KILLED, NO_PERSONS_NOT_INJ, POLICE_ATTEND, ROAD_GEOMETRY, Road Geometry Desc, SEVERITY, SPEED_ZONE, correct_dayofweek]
Index: []

[0 rows x 29 columns]

### Final check the DAY_OF_WEEK and Day Week Description data

In [80]:
# check the incorrect data on sunday
acc_df[(acc_df["DAY_OF_WEEK"] == 1) & (acc_df["Day Week Description"] != "Sunday")]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
1415   T20140002973   2014-10-02     08.00.00              1   
2406   T20140004961   2014-10-03     09.40.00              1   
2420   T20140004999   2014-10-03     15.30.00              1   
2422   T20140005002   2014-10-03     19.10.00              1   
2428   T20140005014   2014-10-03     23.05.00              8   
...             ...          ...          ...            ...   
53462  T20170023233   2017-04-12     18.10.00              4   
53466  T20170023239   2017-04-12     11.30.00              2   
53507  T20170023319   2017-04-12     09.30.00              1   
53617  T20170023580   2017-04-12     07.05.00              1   
53757  T20170023935   2017-08-05     13.55.00              1   

                      Accident Type Desc  DAY_OF_WEEK Day Week Description  \
1415              Collision with vehicle            1               Monday   
2406              Collision with vehicle            1               Monday   
2420              Collision with vehicle            1               Monday   
2422              Collision with vehicle            1               Monday   
2428   No collision and no object struck            1               Monday   
...                                  ...          ...                  ...   
53462      Collision with a fixed object            1               Monday   
53466                  Struck Pedestrian            1               Monday   
53507             Collision with vehicle            1               Monday   
53617             Collision with vehicle            1               Monday   
53757             Collision with vehicle            1               Monday   

       DCA_CODE                                    DCA Description DIRECTORY  \
1415        130     REAR END(VEHICLES IN SAME LANE)                      MEL   
2406        113     RIGHT NEAR (INTERSECTIONS ONLY)                      MEL   
2420        110    CROSS TRAFFIC(INTERSECTIONS ONLY)                     VCS   
2422        111      RIGHT FAR (INTERSECTIONS ONLY)                      MEL   
2428        174  OUT OF CONTROL ON CARRIAGEWAY (ON STRAIGHT)   ...       MEL   
...         ...                                                ...       ...   
53462       181  OFF RIGHT BEND INTO OBJECT/PARKED VEHICLE     ...       VCS   
53466       107  PED ON FOOTHPATH STRUCK BY VEHENTERING/LEAVING...       VCS   
53507       130     REAR END(VEHICLES IN SAME LANE)                      MEL   
53617       130     REAR END(VEHICLES IN SAME LANE)                      MEL   
53757       111      RIGHT FAR (INTERSECTIONS ONLY)                      VCS   

       ... NO_PERSONS_INJ_2 NO_PERSONS_INJ_3 NO_PERSONS_KILLED  \
1415   ...                0                1                 0   
2406   ...                0                1                 0   
2420   ...                2                2                 0   
2422   ...                0                2                 0   
2428   ...                0                1                 0   
...    ...              ...              ...               ...   
53462  ...                1                0                 0   
53466  ...                1                0                 0   
53507  ...                0                1                 0   
53617  ...                0                1                 0   
53757  ...                0                1                 0   

      NO_PERSONS_NOT_INJ  POLICE_ATTEND ROAD_GEOMETRY     Road Geometry Desc  \
1415                   2              2             1     Cross intersection   
2406                   4              1             1     Cross intersection   
2420                   1              1             1     Cross intersection   
2422                   3              1             4  Multiple intersection   
2428                   0              1             5    Not at intersection   
...                  ...            ...           ...               

In [81]:
# check the incorrect data on monday
acc_df[(acc_df["DAY_OF_WEEK"] == 2) & (acc_df["Day Week Description"] != "Monday")]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
1065   T20140002289   2014-04-02     10.40.00              3   
1084   T20140002330   2014-04-02     17.20.00              1   
1096   T20140002356   2014-04-02     21.30.00              1   
1346   T20140002823   2014-04-02     06.50.00              1   
2197   T20140004552   2014-04-03     16.15.00              1   
...             ...          ...          ...            ...   
53476  T20170023267   2017-05-12     16.00.00              1   
53485  T20170023277   2017-05-12     09.00.00              1   
53497  T20170023297   2017-05-12     22.20.00              1   
53552  T20170023438   2017-05-12     15.31.00              1   
53815  T20170024076   2017-05-12     18.20.00              1   

           Accident Type Desc  DAY_OF_WEEK Day Week Description  DCA_CODE  \
1065            Struck animal            2              Tuesday       167   
1084   Collision with vehicle            2              Tuesday       147   
1096   Collision with vehicle            2              Tuesday       121   
1346   Collision with vehicle            2              Tuesday       130   
2197   Collision with vehicle            2              Tuesday       130   
...                       ...          ...                  ...       ...   
53476  Collision with vehicle            2              Tuesday       130   
53485  Collision with vehicle            2              Tuesday       130   
53497  Collision with vehicle            2              Tuesday       113   
53552  Collision with vehicle            2              Tuesday       130   
53815  Collision with vehicle            2              Tuesday       110   

                                         DCA Description DIRECTORY  ...  \
1065               STRUCK ANIMAL                               MEL  ...   
1084   VEHICLE STRIKES ANOTHER VEH WHILE EMERGING FRO...       MEL  ...   
1096               RIGHT THROUGH                               MEL  ...   
1346      REAR END(VEHICLES IN SAME LANE)                      MEL  ...   
2197      REAR END(VEHICLES IN SAME LANE)                      MEL  ...   
...                                                  ...       ...  ...   
53476     REAR END(VEHICLES IN SAME LANE)                      MEL  ...   
53485     REAR END(VEHICLES IN SAME LANE)                      MEL  ...   
53497     RIGHT NEAR (INTERSECTIONS ONLY)                      MEL  ...   
53552     REAR END(VEHICLES IN SAME LANE)                      VCS  ...   
53815    CROSS TRAFFIC(INTERSECTIONS ONLY)                     MEL  ...   

      NO_PERSONS_INJ_2 NO_PERSONS_INJ_3 NO_PERSONS_KILLED NO_PERSONS_NOT_INJ  \
1065                 0                1                 0                  0   
1084                 0                1                 0                  1   
1096                 1                0                 0                  1   
1346                 0                1                 0                  1   
2197                 0                1                 0                  1   
...                ...              ...               ...                ...   
53476                0                1                 0                  1   
53485                0                3                 0                  1   
53497                0                1                 0                  1   
53552                0                1                 0                  1   
53815                0                1                 0                  2   

       POLICE_ATTEND ROAD_GEOMETRY     Road Geometry Desc  SEVERITY  \
1065               1             5    Not at intersection         3   
1084               1             5    Not at intersection         3   
1096               2             2         T intersection         2   
1346               2             5    Not at intersection         3   
2197               1             2         T intersection         3   
...              ...      

In [82]:
# check the incorrect data on tuesday
acc_df[(acc_df["DAY_OF_WEEK"] == 3) & (acc_df["Day Week Description"] != "Tuesday")]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
1160   T20140002472   2014-05-02     17.30.00              1   
1207   T20140002578   2014-05-02     22.25.00              8   
2226   T20140004605   2014-05-03     17.00.00              1   
4122   T20140008346   2014-09-04     14.20.00              1   
4687   T20140009397   2014-07-05     12.52.00              1   
...             ...          ...          ...            ...   
53505  T20170023315   2017-06-12     17.00.00              1   
53529  T20170023384   2017-06-12     20.35.00              1   
53549  T20170023433   2017-06-12     16.00.00              1   
53722  T20170023854   2017-06-12     23.55.00              6   
54233  T20180000958   2017-06-12     17.20.00              1   

                      Accident Type Desc  DAY_OF_WEEK Day Week Description  \
1160              Collision with vehicle            3            Wednesday   
1207   No collision and no object struck            3            Wednesday   
2226              Collision with vehicle            3            Wednesday   
4122              Collision with vehicle            3            Wednesday   
4687              Collision with vehicle            3            Wednesday   
...                                  ...          ...                  ...   
53505             Collision with vehicle            3            Wednesday   
53529             Collision with vehicle            3            Wednesday   
53549             Collision with vehicle            3            Wednesday   
53722  Vehicle overturned (no collision)            3            Wednesday   
54233             Collision with vehicle            3            Wednesday   

       DCA_CODE                                  DCA Description DIRECTORY  \
1160        137         LEFT TURN SIDESWIPE                            MEL   
1207        172       OFF CARRIAGEWAY TO RIGHT                         MEL   
2226        130   REAR END(VEHICLES IN SAME LANE)                      MEL   
4122        130   REAR END(VEHICLES IN SAME LANE)                      MEL   
4687        131              LEFT REAR                                 MEL   
...         ...                                              ...       ...   
53505       121            RIGHT THROUGH                               MEL   
53529       130   REAR END(VEHICLES IN SAME LANE)                      MEL   
53549       130   REAR END(VEHICLES IN SAME LANE)                      VCS   
53722       182     OFF CARRIAGEWAY ON LEFT BEND                       VCS   
54233       110  CROSS TRAFFIC(INTERSECTIONS ONLY)                     VCS   

       ... NO_PERSONS_INJ_2 NO_PERSONS_INJ_3 NO_PERSONS_KILLED  \
1160   ...                1                0                 0   
1207   ...                0                1                 0   
2226   ...                1                0                 0   
4122   ...                0                3                 0   
4687   ...                0                1                 0   
...    ...              ...              ...               ...   
53505  ...                0                1                 0   
53529  ...                0                1                 0   
53549  ...                0                1                 0   
53722  ...                1                0                 0   
54233  ...                0                1                 0   

      NO_PERSONS_NOT_INJ  POLICE_ATTEND ROAD_GEOMETRY   Road Geometry Desc  \
1160                   1              2             1   Cross intersection   
1207                   0              1             1   Cross intersection   
2226                   2              1             5  Not at intersection   
4122                   1              2             1   Cross intersection   
4687                   1              2             5  Not at intersection   
...                  ...            ...           ...                  ...   
53505                  3  

In [83]:
# check the incorrect data on wednesday
acc_df[(acc_df["DAY_OF_WEEK"] == 4) & (acc_df["Day Week Description"] != "Wednesday")]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
210    T20140000539   2014-09-01     16.20.00              1   
1307   T20140002756   2014-06-02     16.30.00              1   
2270   T20140004684   2014-06-03     17.10.00              4   
2273   T20140004693   2014-06-03     17.35.00              1   
2505   T20140005174   2014-06-03     17.45.00              1   
...             ...          ...          ...            ...   
52602  T20170021387   2017-09-11     15.20.00              1   
52617  T20170021415   2017-09-11     17.30.00              1   
53250  T20170022774   2017-09-11     19.04.00              1   
53547  T20170023430   2017-02-11     16.00.00              1   
54064  T20170024663   2017-02-11     12.30.00              1   

                  Accident Type Desc  DAY_OF_WEEK Day Week Description  \
210           Collision with vehicle            4             Thursday   
1307          Collision with vehicle            4             Thursday   
2270   Collision with a fixed object            4             Thursday   
2273          Collision with vehicle            4             Thursday   
2505          Collision with vehicle            4             Thursday   
...                              ...          ...                  ...   
52602         Collision with vehicle            4             Thursday   
52617         Collision with vehicle            4             Thursday   
53250         Collision with vehicle            4             Thursday   
53547         Collision with vehicle            4             Thursday   
54064         Collision with vehicle            4             Thursday   

       DCA_CODE                                    DCA Description DIRECTORY  \
210         130     REAR END(VEHICLES IN SAME LANE)                      MEL   
1307        130     REAR END(VEHICLES IN SAME LANE)                      MEL   
2270        141  U TURN INTO FIXED OBJECT/PARKED VEHICLE       ...             
2273        131                LEFT REAR                                 MEL   
2505        130     REAR END(VEHICLES IN SAME LANE)                      MEL   
...         ...                                                ...       ...   
52602       111      RIGHT FAR (INTERSECTIONS ONLY)                      MEL   
52617       110    CROSS TRAFFIC(INTERSECTIONS ONLY)                     MEL   
53250       133  LANE SIDE SWIPE (VEHICLES IN PARALLEL LANES)  ...       MEL   
53547       134    LANE CHANGE RIGHT (NOT OVERTAKING)                    MEL   
54064       140                  U TURN                                  MEL   

       ... NO_PERSONS_INJ_2 NO_PERSONS_INJ_3 NO_PERSONS_KILLED  \
210    ...                0                1                 0   
1307   ...                0                1                 0   
2270   ...                0                1                 0   
2273   ...                0                1                 0   
2505   ...                0                1                 0   
...    ...              ...              ...               ...   
52602  ...                0                1                 0   
52617  ...                0                1                 0   
53250  ...                0                1                 0   
53547  ...                0                1                 0   
54064  ...                0                1                 0   

      NO_PERSONS_NOT_INJ  POLICE_ATTEND ROAD_GEOMETRY   Road Geometry Desc  \
210                    4              1             2       T intersection   
1307                   2              2             5  Not at intersection   
2270                   0              1             5  Not at intersection   
2273                   2              1             1   Cross intersection   
2505                   2              2             2       T intersection   
...                  ...            ...           ...                  ...   
52602                  1              2           

In [84]:
# check the incorrect data on thursday
acc_df[(acc_df["DAY_OF_WEEK"] == 5) & (acc_df["Day Week Description"] != "Thursday")]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
252    T20140000640   2014-10-01     21.45.00              7   
355    T20140000852   2014-03-01     11.36.00              8   
554    T20140001289   2014-10-01     11.36.00              1   
1576   T20140003284   2014-07-02     00.30.00              6   
3727   T20140007545   2014-11-04     11.25.00              1   
...             ...          ...          ...            ...   
53578  T20170023493   2017-08-12     17.48.00              1   
53582  T20170023505   2017-08-12     18.30.00              1   
53614  T20170023576   2017-08-12     16.20.00              2   
53780  T20170023999   2017-08-12     15.20.00              1   
54232  T20180000925   2017-08-12     14.05.00              1   

                      Accident Type Desc  DAY_OF_WEEK Day Week Description  \
252       Fall from or in moving vehicle            5               Friday   
355    No collision and no object struck            5               Friday   
554               Collision with vehicle            5               Friday   
1576   Vehicle overturned (no collision)            5               Friday   
3727              Collision with vehicle            5               Friday   
...                                  ...          ...                  ...   
53578             Collision with vehicle            5               Friday   
53582             Collision with vehicle            5               Friday   
53614                  Struck Pedestrian            5               Friday   
53780             Collision with vehicle            5               Friday   
54232             Collision with vehicle            5               Friday   

       DCA_CODE                                    DCA Description DIRECTORY  \
252         190           FELL IN/FROM VEHICLE                           MEL   
355         174  OUT OF CONTROL ON CARRIAGEWAY (ON STRAIGHT)   ...       VCS   
554         130     REAR END(VEHICLES IN SAME LANE)                      MEL   
1576        174  OUT OF CONTROL ON CARRIAGEWAY (ON STRAIGHT)   ...       MEL   
3727        130     REAR END(VEHICLES IN SAME LANE)                      MEL   
...         ...                                                ...       ...   
53578       121              RIGHT THROUGH                               MEL   
53582       130     REAR END(VEHICLES IN SAME LANE)                      VCS   
53614       107  PED ON FOOTHPATH STRUCK BY VEHENTERING/LEAVING...       MEL   
53780       160  VEHICLE COLLIDES WITH VEHICLE PARKED ON LEFT O...       VCS   
54232       111      RIGHT FAR (INTERSECTIONS ONLY)                      MEL   

       ... NO_PERSONS_INJ_2 NO_PERSONS_INJ_3 NO_PERSONS_KILLED  \
252    ...                0                1                 0   
355    ...                0                1                 0   
554    ...                0                1                 0   
1576   ...                0                1                 0   
3727   ...                1                0                 0   
...    ...              ...              ...               ...   
53578  ...                0                1                 0   
53582  ...                0                3                 0   
53614  ...                0                1                 0   
53780  ...                0                1                 0   
54232  ...                0                1                 0   

      NO_PERSONS_NOT_INJ  POLICE_ATTEND ROAD_GEOMETRY   Road Geometry Desc  \
252                    1              1             5  Not at intersection   
355                    0              2             5  Not at intersection   
554                    2              2             2       T intersection   
1576                   0              2             1   Cross intersection   
3727                   2              1             2       T intersection   
...                  ...            ...           ...                  ...   
53

In [85]:
# check the incorrect data on friday
acc_df[(acc_df["DAY_OF_WEEK"] == 6) & (acc_df["Day Week Description"] != "Friday")]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
95     T20140000240   2014-04-01     16.00.00              2   
168    T20140000433   2014-04-01     16.35.00              1   
507    T20140001192   2014-04-01     12.00.00              8   
972    T20140002110   2014-01-02     09.10.00              8   
1212   T20140002586   2014-01-02     13.20.00              1   
...             ...          ...          ...            ...   
53600  T20170023539   2017-09-12     16.45.00              1   
53604  T20170023549   2017-09-12     19.00.00              1   
53606  T20170023558   2017-09-12     15.20.00              1   
53621  T20170023588   2017-09-12     15.54.00              1   
53846  T20170024148   2017-09-12     21.45.00              1   

                      Accident Type Desc  DAY_OF_WEEK Day Week Description  \
95                     Struck Pedestrian            6             Saturday   
168               Collision with vehicle            6             Saturday   
507    No collision and no object struck            6             Saturday   
972    No collision and no object struck            6             Saturday   
1212              Collision with vehicle            6             Saturday   
...                                  ...          ...                  ...   
53600             Collision with vehicle            6             Saturday   
53604             Collision with vehicle            6             Saturday   
53606             Collision with vehicle            6             Saturday   
53621             Collision with vehicle            6             Saturday   
53846             Collision with vehicle            6             Saturday   

       DCA_CODE                                    DCA Description DIRECTORY  \
95          109  ANY MANOEUVRE INVOLVING PED NOT INCLUDED IN DC...       MEL   
168         130     REAR END(VEHICLES IN SAME LANE)                      MEL   
507         174  OUT OF CONTROL ON CARRIAGEWAY (ON STRAIGHT)   ...       VCS   
972         174  OUT OF CONTROL ON CARRIAGEWAY (ON STRAIGHT)   ...       MEL   
1212        137           LEFT TURN SIDESWIPE                            MEL   
...         ...                                                ...       ...   
53600       130     REAR END(VEHICLES IN SAME LANE)                      MEL   
53604       121              RIGHT THROUGH                               MEL   
53606       121              RIGHT THROUGH                               MEL   
53621       110    CROSS TRAFFIC(INTERSECTIONS ONLY)                     MEL   
53846       111      RIGHT FAR (INTERSECTIONS ONLY)                      MEL   

       ... NO_PERSONS_INJ_2 NO_PERSONS_INJ_3 NO_PERSONS_KILLED  \
95     ...                0                1                 0   
168    ...                0                1                 0   
507    ...                1                0                 0   
972    ...                0                1                 0   
1212   ...                0                1                 0   
...    ...              ...              ...               ...   
53600  ...                0                1                 0   
53604  ...                0                1                 0   
53606  ...                0                1                 0   
53621  ...                0                1                 0   
53846  ...                0                1                 0   

      NO_PERSONS_NOT_INJ  POLICE_ATTEND ROAD_GEOMETRY     Road Geometry Desc  \
95                     1              2             2         T intersection   
168                    1              2             4  Multiple intersection   
507                    0              2             5    Not at intersection   
972                    1              1             2         T intersection   
1212                   1              2             5    Not at intersection   
...                  ...            ...           ...               

In [86]:
# check the incorrect data on saturday
acc_df[(acc_df["DAY_OF_WEEK"] == 7) & (acc_df["Day Week Description"] != "Saturday")]

Empty DataFrame
Columns: [ACCIDENT_NO, ACCIDENTDATE, ACCIDENTTIME, ACCIDENT_TYPE, Accident Type Desc, DAY_OF_WEEK, Day Week Description, DCA_CODE, DCA Description, DIRECTORY, EDITION, PAGE, GRID_REFERENCE_X, GRID_REFERENCE_Y, LIGHT_CONDITION, Light Condition Desc, NODE_ID, NO_OF_VEHICLES, NO_PERSONS, NO_PERSONS_INJ_2, NO_PERSONS_INJ_3, NO_PERSONS_KILLED, NO_PERSONS_NOT_INJ, POLICE_ATTEND, ROAD_GEOMETRY, Road Geometry Desc, SEVERITY, SPEED_ZONE, correct_dayofweek]
Index: []

[0 rows x 29 columns]

After having the final checking, the findings are:

1. All of the data in "Saturday" are correct.

2. After updating the data in the **DAY_OF_WEEK** and **Day Week Description** columns, the rest of incorrect data may happend in the **ACCIDENTDATE** column itself, **DAY_OF_WEEK** column itself, or **Day Week Description** column itself. Therefore, before discussing with clent, these rows will be removed to eliminate the accuracy of analysing the data.

### Remove the rows data by specific index

In [87]:
# change the value in correct_dayofweek column from number to string
week_day = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]

for index in range(0, 7):
    idx = acc_df[(acc_df["DAY_OF_WEEK"] == index + 1) & (acc_df["Day Week Description"] != week_day[index])].index.values
    for rows in idx:
        acc_df.drop([rows], inplace = True)

## 2. Check with the node_id in the acc_df and acc_lo_df

In [88]:
# check the acc_lc_df first
acc_lo_df[(acc_lo_df["NODE_ID"] < 0) & (acc_lo_df.isnull().values.any())] 

ACCIDENT_NO  NODE_ID  ROAD_ROUTE_1 ROAD_NAME ROAD_TYPE ROAD_NAME_INT  \
41      T20060000265      -10           NaN       NaN       NaN           NaN   
291     T20060001419      -10           NaN       NaN       NaN           NaN   
294     T20060001426       -3           NaN       NaN       NaN           NaN   
297     T20060001431       -3           NaN       NaN       NaN           NaN   
349     T20060001717      -10           NaN       NaN       NaN           NaN   
...              ...      ...           ...       ...       ...           ...   
115418  T20140011928      -10           NaN       NaN       NaN           NaN   
115775  T20140012601      -10           NaN       NaN       NaN           NaN   
116273  T20140013537      -10           NaN       NaN       NaN           NaN   
120019  T20140020819      -10           NaN       NaN       NaN           NaN   
148441  T20160020719       -1           NaN       NaN       NaN           NaN   

       ROAD_TYPE_INT  DISTANCE_LOCATION DIRECTION_LOCATION  NEAREST_KM_POST  \
41               NaN                NaN                NaN              NaN   
291              NaN                NaN                NaN              NaN   
294              NaN                NaN                NaN              NaN   
297              NaN                NaN                NaN              NaN   
349              NaN                NaN                NaN              NaN   
...              ...                ...                ...              ...   
115418           NaN                NaN                NaN              NaN   
115775           NaN                NaN                NaN              NaN   
116273           NaN                NaN                NaN              NaN   
120019           NaN                NaN                NaN              NaN   
148441           NaN                NaN                NaN              NaN   

       OFF_ROAD_LOCATION  
41                   NaN  
291                  NaN  
294                  NaN  
297                  NaN  
349                  NaN  
...                  ...  
115418               NaN  
115775               NaN  
116273               NaN  
120019               NaN  
148441               NaN  

[875 rows x 11 columns]

It has the 875 rows include the null value and the node_id is less than 0, which is incorrect value in the node_id. Because the node_id should start with 1 not the negative number. Therefore, these 875 rows will be removed from the acc_lo_df.

In [89]:
# removed the null value and the node_id shows anonymous status

idx = acc_lo_df[(acc_lo_df["NODE_ID"] < 0) & (acc_lo_df.isnull().values.any())].index.values

for index in idx:
    acc_lo_df.drop([index], inplace = True)

In [90]:
# check the acc_df secondly
acc_df[acc_df["NODE_ID"] < 0]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
107    T20140000268   2014-05-01     09.00.00              8   
1770   T20140003678   2014-02-19     02.40.00              4   
1784   T20140003709   2014-02-22     09.45.00              8   
3737   T20140007565   2014-02-04     17.30.00              1   
3857   T20140007808   2014-04-15     08.40.00              4   
4004   T20140008096   2014-04-19     09.55.00              8   
4999   T20140009982   2014-05-13     22.00.00              3   
6037   T20140011928   2014-09-06     18.30.00              4   
6389   T20140012601   2014-09-06     10.45.00              8   
6878   T20140013537   2014-06-22     11.30.00              4   
10560  T20140020819   2014-01-10     18.30.00              1   
38926  T20160020719   2016-08-14     04.39.00              1   

                      Accident Type Desc  DAY_OF_WEEK Day Week Description  \
107    No collision and no object struck            1               Sunday   
1770       Collision with a fixed object            4            Wednesday   
1784   No collision and no object struck            7             Saturday   
3737              Collision with vehicle            4            Wednesday   
3857       Collision with a fixed object            3              Tuesday   
4004   No collision and no object struck            7             Saturday   
4999                       Struck animal            3              Tuesday   
6037       Collision with a fixed object            2               Monday   
6389   No collision and no object struck            2               Monday   
6878       Collision with a fixed object            1               Sunday   
10560             Collision with vehicle            4            Wednesday   
38926             Collision with vehicle            0               Sunday   

       DCA_CODE                                    DCA Description DIRECTORY  \
107         174  OUT OF CONTROL ON CARRIAGEWAY (ON STRAIGHT)   ...       NaN   
1770        141  U TURN INTO FIXED OBJECT/PARKED VEHICLE       ...       NaN   
1784        174  OUT OF CONTROL ON CARRIAGEWAY (ON STRAIGHT)   ...       NaN   
3737        163  VEHICLE STRIKES DOOR OF PARKED/STATIONARY VEHI...       NaN   
3857        146  REVERSING INTO FIXED OBJECT/PARKED VEHICLE    ...       NaN   
4004        174  OUT OF CONTROL ON CARRIAGEWAY (ON STRAIGHT)   ...       NaN   
4999        167              STRUCK ANIMAL                               NaN   
6037        175     OFF END OF ROAD/T-INTERSECTION.                      NaN   
6389        174  OUT OF CONTROL ON CARRIAGEWAY (ON STRAIGHT)   ...       NaN   
6878        171  LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICL...       NaN   
10560       130     REAR END(VEHICLES IN SAME LANE)                      NaN   
38926       198  OTHER ACCIDENTS NOT CLASSIFIABLE ELSEWHERE    ...       NaN   

       ... NO_PERSONS_INJ_2 NO_PERSONS_INJ_3 NO_PERSONS_KILLED  \
107    ...                0                1                 0   
1770   ...                0                1                 0   
1784   ...                0                1                 0   
3737   ...                0                1                 0   
3857   ...                0                1                 0   
4004   ...                0                1                 0   
4999   ...                0                1                 0   
6037   ...                0                1                 0   
6389   ...                0                1                 0   
6878   ...                0                1                 0   
10560  ...                0                1                 0   
38926  ...                0                1                 0   

      NO_PERSONS_NOT_INJ  POLICE_ATTEND ROAD_GEOMETRY   Road Geometry Desc  \
107                    0              1             5  Not at intersection   
1770                   1              1             5  Not at intersection   
1784                   0  

In [91]:
# check the acc_df secondly with the null value column
acc_df[acc_df["NODE_ID"] < 0].isna().any()

ACCIDENT_NO             False
ACCIDENTDATE            False
ACCIDENTTIME            False
ACCIDENT_TYPE           False
Accident Type Desc      False
DAY_OF_WEEK             False
Day Week Description    False
DCA_CODE                False
DCA Description         False
DIRECTORY                True
EDITION                  True
PAGE                     True
GRID_REFERENCE_X         True
GRID_REFERENCE_Y         True
LIGHT_CONDITION         False
Light Condition Desc    False
NODE_ID                 False
NO_OF_VEHICLES          False
NO_PERSONS              False
NO_PERSONS_INJ_2        False
NO_PERSONS_INJ_3        False
NO_PERSONS_KILLED       False
NO_PERSONS_NOT_INJ      False
POLICE_ATTEND           False
ROAD_GEOMETRY           False
Road Geometry Desc      False
SEVERITY                False
SPEED_ZONE              False
correct_dayofweek       False
dtype: bool

It has 13 rows included the node_id less than 0. However, these five columns show that there are including the null value, which is "DIRECTORY", "EDITION", "PAGE", "GRID_REFERENCE_X", "GRID_REFERENCE_Y".

According to the previous analysis, these five columns will be removed, also the node_id does not contain too much information when analysing the accident data. So, in here, it only removes these five columns instead of deleting these 13 rows.

In [92]:
# check the node_df lastly
node_df[node_df["NODE_ID"] < 0]

Empty DataFrame
Columns: [ACCIDENT_NO, NODE_ID, NODE_TYPE, AMG_X, AMG_Y, LGA_NAME, Lga Name All, Region Name, Lat, Long, Postcode No]
Index: []

In the node_df, it does not contain any node_id less than 0.

## 3. Check with the road_route_1 in the acc_df

In [93]:
# check the acc_lc_df in the road_route_1 column less than 0
acc_lo_df[(acc_lo_df["ROAD_ROUTE_1"] < 0) & (acc_lo_df.isnull().values.any())] 

ACCIDENT_NO  NODE_ID  ROAD_ROUTE_1       ROAD_NAME ROAD_TYPE  \
236     T20060001147   205508          -1.0             NaN       NaN   
394     T20060001884   301499          -1.0             APM     TRACK   
1664    T20060006194    26040          -1.0             NaN       NaN   
1867    T20060006811   202253          -1.0             NaN       NaN   
1904    T20060006934   202429          -1.0             NaN       NaN   
...              ...      ...           ...             ...       ...   
164522  T20180002249   327352          -1.0          FISHER     COURT   
164554  T20180002329   327203          -1.0        BUNGOWER      ROAD   
164621  T20180002537   327205          -1.0  DONALD CAMERON     DRIVE   
164692  T20180002795   327638          -1.0          SLATER    STREET   
164741  T20180003291   327321          -1.0       MCKIMMIES      ROAD   

       ROAD_NAME_INT ROAD_TYPE_INT  DISTANCE_LOCATION DIRECTION_LOCATION  \
236              NaN           NaN                0.0                 NK   
394              NaN           NaN                0.0                 NK   
1664             NaN           NaN                0.0                 NK   
1867             NaN           NaN                0.0                 NK   
1904             NaN           NaN                0.0                 NK   
...              ...           ...                ...                ...   
164522           NaN           NaN                0.0                 NK   
164554           NaN           NaN                0.0                 NK   
164621           NaN           NaN                0.0                 NK   
164692           NaN           NaN                0.0                 NK   
164741           NaN           NaN                0.0                 NK   

        NEAREST_KM_POST OFF_ROAD_LOCATION  
236                 NaN               NaN  
394                 NaN               NaN  
1664                NaN               NaN  
1867                NaN               NaN  
1904                NaN               NaN  
...                 ...               ...  
164522              NaN               NaN  
164554              NaN               NaN  
164621              NaN               NaN  
164692              NaN               NaN  
164741              NaN               NaN  

[273 rows x 11 columns]

In the road_route_1 column, when it is less than 0, it contains 273 rows. And in this 273 rows, the majority columns show on the null value. Therefore, those 273 rows will be removed.

In [94]:
# removed the null value and the road_route_1 shows anonymous status

idx = acc_lo_df[(acc_lo_df["ROAD_ROUTE_1"] < 0) & (acc_lo_df.isnull().values.any())].index.values

for index in idx:
    acc_lo_df.drop([index], inplace = True)

## Delete the column with not containing too much information for analysing the accidents

In [95]:
# remove the columns in the acc_df
# check_list already includes "DIRECTORY", "EDITION", "PAGE", "GRID_REFERENCE_X", "GRID_REFERENCE_Y"

for col in check_list:
    del acc_df[col]

In [96]:
# remove the node_id in the acc_df
del acc_df["NODE_ID"]
del acc_df["correct_dayofweek"]

In [97]:
# remove the nearest_km_post, off_road_location, node_id in the acc_df
del acc_lo_df["NEAREST_KM_POST"]
del acc_lo_df["OFF_ROAD_LOCATION"]
del acc_lo_df["NODE_ID"]
del acc_lo_df["DISTANCE_LOCATION"]

In [98]:
# remove the amg_x, amg_y node_id in the node_df
del node_df["AMG_X"]
del node_df["AMG_Y"]
del node_df["NODE_ID"]

## Add the road_route_1 description column in acc_lo_df

In [99]:
# copy the column from ROAD_ROUTE_1 to ROAD_ROUTE_1_DES
acc_lo_df["ROAD_ROUTE_1_DES"] = acc_lo_df["ROAD_ROUTE_1"]

In [100]:
# add the "2000-2999 Freeways or Highways" inforamtion in road_route_1 descritption

acc_lo_df.loc[(acc_lo_df["ROAD_ROUTE_1"] >= 2000) 
              & (acc_lo_df["ROAD_ROUTE_1"] <= 2999), "ROAD_ROUTE_1_DES"] = "Freeways or Highways"

In [101]:
# add the "3000-3999 Forest Rds" inforamtion in road_route_1 descritption

acc_lo_df.loc[(acc_lo_df["ROAD_ROUTE_1"] >= 3000) 
              & (acc_lo_df["ROAD_ROUTE_1"] <= 3999), "ROAD_ROUTE_1_DES"] = "Forest Rds"

In [102]:
# add the "4000-4999 Tourist Rds" inforamtion in road_route_1 descritption

acc_lo_df.loc[(acc_lo_df["ROAD_ROUTE_1"] >= 4000) 
              & (acc_lo_df["ROAD_ROUTE_1"] <= 4999), "ROAD_ROUTE_1_DES"] = "Tourist Rds"

In [103]:
# add the "5000-5999 Main Rds" inforamtion in road_route_1 descritption

acc_lo_df.loc[(acc_lo_df["ROAD_ROUTE_1"] >= 5000) 
              & (acc_lo_df["ROAD_ROUTE_1"] <= 5999), "ROAD_ROUTE_1_DES"] = "Main Rds"

In [104]:
# add the "7000-7999 Ramps (mainly Freeway ramps)" inforamtion in road_route_1 descritption

acc_lo_df.loc[(acc_lo_df["ROAD_ROUTE_1"] >= 7000) 
              & (acc_lo_df["ROAD_ROUTE_1"] <= 7999), "ROAD_ROUTE_1_DES"] = "Ramps (mainly Freeway ramps)"

In [105]:
# add the "9999 Unclassified Roads" inforamtion in road_route_1 descritption

acc_lo_df.loc[(acc_lo_df["ROAD_ROUTE_1"] >= 9999), "ROAD_ROUTE_1_DES"] = "Unclassified Roads"

In [106]:
# change the column order
col_list = acc_lo_df.columns.to_list()
col_list.insert(2, "ROAD_ROUTE_1_DES")
col_list.pop()

'ROAD_ROUTE_1_DES'

In [107]:
# reorder the column name in the acc_lo_df
acc_lo_df = acc_lo_df[col_list]

## Double-Checked the missing value and anonymous in acc_df, acc_lo_df, and node_df

In [108]:
# check missing value in acc_df
acc_df.count()

ACCIDENT_NO             51836
ACCIDENTDATE            51836
ACCIDENTTIME            51836
ACCIDENT_TYPE           51836
Accident Type Desc      51836
DAY_OF_WEEK             51836
Day Week Description    51836
DCA_CODE                51836
DCA Description         51836
LIGHT_CONDITION         51836
Light Condition Desc    51836
NO_OF_VEHICLES          51836
NO_PERSONS              51836
NO_PERSONS_INJ_2        51836
NO_PERSONS_INJ_3        51836
NO_PERSONS_KILLED       51836
NO_PERSONS_NOT_INJ      51836
POLICE_ATTEND           51836
ROAD_GEOMETRY           51836
Road Geometry Desc      51836
SEVERITY                51836
SPEED_ZONE              51836
dtype: int64

In [109]:
# check the missing value in acc_lo_df
acc_lo_df.count()

ACCIDENT_NO           163641
ROAD_ROUTE_1          163640
ROAD_ROUTE_1_DES      163640
ROAD_NAME             163640
ROAD_TYPE             161964
ROAD_NAME_INT         163498
ROAD_TYPE_INT         162206
DIRECTION_LOCATION    163640
dtype: int64

In [110]:
# check the missing value in node_df
node_df.count()

ACCIDENT_NO     163913
NODE_TYPE       163913
LGA_NAME        163913
Lga Name All    163913
Region Name     163913
Lat             163913
Long            163913
Postcode No     163913
dtype: int64

In the main dataset, which is the accident dataset, it does not contain any missing value and it includes 51,864 rows data. On the other hand, in the accident location and node dataset, it has few missing value between these two datasets. However, these two datasets contain around 160K rows data which the triple number rows compare with the accident dataset.

Therefore, the missing value may not exist aftering joining all of the table.

In [111]:
# check missing value in acc_df
acc_df.describe()

ACCIDENT_TYPE   DAY_OF_WEEK      DCA_CODE  LIGHT_CONDITION  \
count   51836.000000  51836.000000  51836.000000     51836.000000   
mean        2.271935      4.037484    139.843391         1.891697   
std         2.028888      2.017671     26.555471         1.617797   
min         1.000000      0.000000    100.000000         1.000000   
25%         1.000000      2.000000    120.000000         1.000000   
50%         1.000000      4.000000    130.000000         1.000000   
75%         4.000000      6.000000    171.000000         2.000000   
max         9.000000      7.000000    199.000000         9.000000   

       NO_OF_VEHICLES    NO_PERSONS  NO_PERSONS_INJ_2  NO_PERSONS_INJ_3  \
count    51836.000000  51836.000000      51836.000000      51836.000000   
mean         1.802801      2.388282          0.335288          0.910622   
std          0.751555      1.558580          0.592625          0.769122   
min          1.000000      1.000000          0.000000          0.000000   
25%          1.000000      2.000000          0.000000          0.000000   
50%          2.000000      2.000000          0.000000          1.000000   
75%          2.000000      3.000000          1.000000          1.000000   
max         14.000000     89.000000         16.000000         25.000000   

       NO_PERSONS_KILLED  NO_PERSONS_NOT_INJ  POLICE_ATTEND  ROAD_GEOMETRY  \
count       51836.000000        51836.000000   51836.000000   51836.000000   
mean            0.019832            1.122097       1.285882       3.410603   
std             0.152381            1.363798       0.649914       1.763803   
min             0.000000            0.000000       1.000000       1.000000   
25%             0.000000            0.000000       1.000000       2.000000   
50%             0.000000            1.000000       1.000000       5.000000   
75%             0.000000            1.000000       2.000000       5.000000   
max             4.000000           87.000000       9.000000       9.000000   

           SEVERITY    SPEED_ZONE  
count  51836.000000  51836.000000  
mean       2.676422    130.017883  
std        0.505542    231.015572  
min        1.000000     30.000000  
25%        2.000000     60.000000  
50%        3.000000     60.000000  
75%        3.000000     80.000000  
max        4.000000    999.000000

In [112]:
# look at the row which involves 89 persons in the accident
acc_df[acc_df["NO_PERSONS"] == 89] 

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
22544  T20150016376   2015-06-08     14.00.00              1   

           Accident Type Desc  DAY_OF_WEEK Day Week Description  DCA_CODE  \
22544  Collision with vehicle            5             Thursday       192   

                            DCA Description  LIGHT_CONDITION  ... NO_PERSONS  \
22544  STRUCK TRAIN                                        1  ...         89   

       NO_PERSONS_INJ_2  NO_PERSONS_INJ_3  NO_PERSONS_KILLED  \
22544                 1                 1                  0   

       NO_PERSONS_NOT_INJ  POLICE_ATTEND  ROAD_GEOMETRY   Road Geometry Desc  \
22544                  87              1              5  Not at intersection   

       SEVERITY SPEED_ZONE  
22544         2         80  

[1 rows x 22 columns]

After looking at this data, the definitions for classifying accidents shows that it happended in the struck train accident. So, it probably has the numberous people invloved in the accident, which means it was not the outlier.

In [113]:
# check missing value in acc_df
acc_lo_df.describe()

ROAD_ROUTE_1
count  163640.00000
mean     6283.31323
std      3102.59236
min         0.00000
25%      2880.00000
50%      5770.00000
75%      9999.00000
max      9999.00000

In [114]:
# the anonymous in the ROAD_ROUTE_1 column when the ROAD_ROUTE_1 == 0
acc_lo_df[acc_lo_df["ROAD_ROUTE_1"] == 0]

ACCIDENT_NO  ROAD_ROUTE_1 ROAD_ROUTE_1_DES ROAD_NAME ROAD_TYPE  \
76892   T20110031804           0.0                0                       
83690   T20120004720           0.0                0                       
88949   T20120016014           0.0                0                       
93419   T20120025493           0.0                0                       
100967  T20130011361           0.0                0                       
...              ...           ...              ...       ...       ...   
163683  T20170024913           0.0                0                       
164027  T20180000821           0.0                0                       
164227  T20180001354           0.0                0                       
164465  T20180002086           0.0                0                       
164577  T20180002398           0.0                0                       

       ROAD_NAME_INT         ROAD_TYPE_INT DIRECTION_LOCATION  
76892    PRINCES FWD  HIGHWAY SERVICE ROAD                  W  
83690        BULLEEN                  ROAD                  S  
88949       LONSDALE                STREET                  N  
93419          JONES                  ROAD                 NW  
100967       KNOCKER                 TRACK                  N  
...              ...                   ...                ...  
163683    DEAD HORSE                  LANE                  S  
164027          FRYS                  LANE                 NW  
164227     GAINSFORD                   WAY                  W  
164465       DINGLEY                BYPASS                  S  
164577    DEAD HORSE                  LANE                  S  

[4276 rows x 8 columns]

It might be eliminating the problem after joining those three datafram. So, it will check later.

In [115]:
# check missing value in acc_df
node_df.describe()

Lat           Long    Postcode No
count  163913.000000  163913.000000  163913.000000
mean      -37.712237     144.979509    3309.607084
std         0.569298       0.814169     301.421139
min       -39.032320     140.966180    3000.000000
25%       -37.951220     144.869610    3074.000000
50%       -37.818170     145.020000    3175.000000
75%       -37.705720     145.206960    3550.000000
max       -34.062380     149.757470    3996.000000

It looks like does not have any anonymous problem in the node_df. 

## Join three dataframe by accident_no

In [116]:
join1_df = pd.merge(acc_df, acc_lo_df, on = "ACCIDENT_NO")

In [117]:
join1_df[:5]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
0  T20140000003   2014-01-01     00.30.00              6   
1  T20140000006   2014-01-01     01.30.00              4   
2  T20140000007   2014-01-01     03.20.00              1   
3  T20140000011   2014-01-01     03.35.00              1   
4  T20140000017   2014-01-01     08.25.00              1   

                  Accident Type Desc  DAY_OF_WEEK Day Week Description  \
0  Vehicle overturned (no collision)            4            Wednesday   
1      Collision with a fixed object            4            Wednesday   
2             Collision with vehicle            4            Wednesday   
3             Collision with vehicle            4            Wednesday   
4             Collision with vehicle            4            Wednesday   

   DCA_CODE                                    DCA Description  \
0       180      OFF CARRIAGEWAY ON RIGHT BEND                   
1       171  LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICL...   
2       110    CROSS TRAFFIC(INTERSECTIONS ONLY)                 
3       160  VEHICLE COLLIDES WITH VEHICLE PARKED ON LEFT O...   
4       160  VEHICLE COLLIDES WITH VEHICLE PARKED ON LEFT O...   

   LIGHT_CONDITION  ...   Road Geometry Desc  SEVERITY  SPEED_ZONE  \
0                3  ...  Not at intersection         3          60   
1                5  ...  Not at intersection         2         100   
2                3  ...   Cross intersection         3          60   
3                3  ...       T intersection         3          50   
4                1  ...  Not at intersection         3          60   

   ROAD_ROUTE_1      ROAD_ROUTE_1_DES            ROAD_NAME  ROAD_TYPE  \
0        5877.0              Main Rds   FOOTSCRAY-SUNSHINE       ROAD   
1        9999.0    Unclassified Roads         GREIGS CREEK       ROAD   
2        2080.0  Freeways or Highways  HODDLE STREET -PUNT       ROAD   
3        9999.0    Unclassified Roads            KOOLAMARA  BOULEVARD   
4        5736.0              Main Rds            NICHOLSON     STREET   

   ROAD_NAME_INT  ROAD_TYPE_INT DIRECTION_LOCATION  
0      GRAINGERS           ROAD                 SE  
1   SPRING CREEK           ROAD                  W  
2     WELLINGTON         PARADE                  S  
3        PARINGA          DRIVE                  W  
4        BROOKES       CRESCENT                  S  

[5 rows x 29 columns]

In [118]:
join2_df = pd.merge(join1_df, node_df, on = "ACCIDENT_NO")

In [119]:
join2_df[:5]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
0  T20140000003   2014-01-01     00.30.00              6   
1  T20140000006   2014-01-01     01.30.00              4   
2  T20140000007   2014-01-01     03.20.00              1   
3  T20140000011   2014-01-01     03.35.00              1   
4  T20140000017   2014-01-01     08.25.00              1   

                  Accident Type Desc  DAY_OF_WEEK Day Week Description  \
0  Vehicle overturned (no collision)            4            Wednesday   
1      Collision with a fixed object            4            Wednesday   
2             Collision with vehicle            4            Wednesday   
3             Collision with vehicle            4            Wednesday   
4             Collision with vehicle            4            Wednesday   

   DCA_CODE                                    DCA Description  \
0       180      OFF CARRIAGEWAY ON RIGHT BEND                   
1       171  LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICL...   
2       110    CROSS TRAFFIC(INTERSECTIONS ONLY)                 
3       160  VEHICLE COLLIDES WITH VEHICLE PARKED ON LEFT O...   
4       160  VEHICLE COLLIDES WITH VEHICLE PARKED ON LEFT O...   

   LIGHT_CONDITION  ... ROAD_NAME_INT  ROAD_TYPE_INT  DIRECTION_LOCATION  \
0                3  ...     GRAINGERS           ROAD                  SE   
1                5  ...  SPRING CREEK           ROAD                   W   
2                3  ...    WELLINGTON         PARADE                   S   
3                3  ...       PARINGA          DRIVE                   W   
4                1  ...       BROOKES       CRESCENT                   S   

   NODE_TYPE     LGA_NAME     Lga Name All                     Region Name  \
0          N  MARIBYRNONG      MARIBYRNONG  METROPOLITAN NORTH WEST REGION   
1          N   WELLINGTON       WELLINGTON                  EASTERN REGION   
2          I    MELBOURNE  YARRA,MELBOURNE  METROPOLITAN NORTH WEST REGION   
3          I         KNOX             KNOX  METROPOLITAN SOUTH EAST REGION   
4          N        YARRA            YARRA  METROPOLITAN NORTH WEST REGION   

        Lat       Long Postcode No  
0 -37.80202  144.88100        3012  
1 -38.45802  146.70151        3971  
2 -37.81755  144.99001        3121  
3 -37.89864  145.28114        3156  
4 -37.78711  144.97684        3068  

[5 rows x 36 columns]

### Check the missing value

In [120]:
# check the missing value and anonymous problem in the final merge dataframe join2_df
join2_df.isna().any()

ACCIDENT_NO             False
ACCIDENTDATE            False
ACCIDENTTIME            False
ACCIDENT_TYPE           False
Accident Type Desc      False
DAY_OF_WEEK             False
Day Week Description    False
DCA_CODE                False
DCA Description         False
LIGHT_CONDITION         False
Light Condition Desc    False
NO_OF_VEHICLES          False
NO_PERSONS              False
NO_PERSONS_INJ_2        False
NO_PERSONS_INJ_3        False
NO_PERSONS_KILLED       False
NO_PERSONS_NOT_INJ      False
POLICE_ATTEND           False
ROAD_GEOMETRY           False
Road Geometry Desc      False
SEVERITY                False
SPEED_ZONE              False
ROAD_ROUTE_1            False
ROAD_ROUTE_1_DES        False
ROAD_NAME               False
ROAD_TYPE                True
ROAD_NAME_INT            True
ROAD_TYPE_INT            True
DIRECTION_LOCATION      False
NODE_TYPE               False
LGA_NAME                False
Lga Name All            False
Region Name             False
Lat       

It has three columns contain the missing value which are ROAD_TYPE, ROAD_NAME_INT, and ROAD_TYPE_INT.

In [121]:
# check the column of ROAD_TYPE and ROAD_TYPE_INT to deal with the missing value
join2_df[(join2_df["ROAD_TYPE"].isnull()) & (join2_df["ROAD_TYPE_INT"].notnull())]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
48     T20140000132   2014-01-01     22.21.00              1   
83     T20140000236   2014-04-01     16.39.00              1   
173    T20140000475   2014-08-01     19.50.00              9   
195    T20140000534   2014-09-01     17.26.00              1   
213    T20140000582   2014-10-01     10.00.00              1   
...             ...          ...          ...            ...   
51404  T20170024405   2017-12-21     16.15.00              1   
51469  T20170024572   2017-12-24     08.57.00              1   
51534  T20170024719   2017-11-18     14.00.00              1   
51655  T20180000427   2016-04-14     18.15.00              1   
51684  T20180001539   2017-11-14     12.00.00              4   

                  Accident Type Desc  DAY_OF_WEEK Day Week Description  \
48            Collision with vehicle            4            Wednesday   
83            Collision with vehicle            7             Saturday   
173                   Other accident            4            Wednesday   
195           Collision with vehicle            5             Thursday   
213           Collision with vehicle            6               Friday   
...                              ...          ...                  ...   
51404         Collision with vehicle            5             Thursday   
51469         Collision with vehicle            1               Sunday   
51534         Collision with vehicle            7             Saturday   
51655         Collision with vehicle            5             Thursday   
51684  Collision with a fixed object            3              Tuesday   

       DCA_CODE                                    DCA Description  \
48          160  VEHICLE COLLIDES WITH VEHICLE PARKED ON LEFT O...   
83          160  VEHICLE COLLIDES WITH VEHICLE PARKED ON LEFT O...   
173         139  OTHER SAME DIRECTION-MANOUEVRES NOT INCLUDED I...   
195         135    LANE CHANGE LEFT (NOT OVERTAKING)                 
213         140                  U TURN                              
...         ...                                                ...   
51404       114  TWO RIGHT TURNING (INTERSECTIONS ONLY)              
51469       134    LANE CHANGE RIGHT (NOT OVERTAKING)                
51534       120         HEAD ON (NOT OVERTAKING)                     
51655       130     REAR END(VEHICLES IN SAME LANE)                  
51684       179  OTHER ACCIDENTS-OFF STRAIGHT NOT INCLUDED IN D...   

       LIGHT_CONDITION  ...          ROAD_NAME_INT  ROAD_TYPE_INT  \
48                   6  ...               MEREDITH         STREET   
83                   1  ...   CITYLINK IN-YARRA OF           RAMP   
173                  2  ...                  BYRON         STREET   
195                  1  ...  YARRA-CITYLINK OUT ON           RAMP   
213                  1  ...                   WEBB         STREET   
...                ...  ...                    ...            ...   
51404                1  ...               TRUEMANS           ROAD   
51469                1  ...                  DENDY         STREET   
51534                1  ...                   SAND           ROAD   
51655                9  ...                LORIMER         STREET   
51684                9  ...                VERNIER         STREET   

       DIRECTION_LOCATION  NODE_TYPE              LGA_NAME  \
48                      S          N          PORT PHILLIP   
83                      W          N                 YARRA   
173                     N          I          PORT PHILLIP   
195                     E          N                 YARRA   
213                    NE          I  MORNINGTON PENINSULA   
...                   ...        ...                   ...   
51404                   E          I  MORNINGTON PENINSULA   
51469                   S          N               BAYSIDE   
51534                  NE          N           COLAC OTWAY   
51655                   N          N             MELBOURNE  

In [122]:
# check the value inside in the road_type column
rord_tp_list = join2_df["ROAD_TYPE"].values.tolist()
rord_tp_list = set(rord_tp_list)
rord_tp_list

{' ',
 'ALLEY',
 'AVENUE',
 'BEND',
 'BOULEVARD',
 'BOULEVARDE',
 'BREAK',
 'BYPASS',
 'CAUSEWAY',
 'CENTRE',
 'CIRCUIT',
 'CLOSE',
 'CONCOURSE',
 'COURT',
 'CRESCENT',
 'CUTTING',
 'DRIVE',
 'EAST',
 'ESPLANADE',
 'FIRELINE',
 'FREEWAY',
 'GRANGE',
 'GREEN',
 'GROVE',
 'HIGHWAY',
 'LANE',
 'LINK',
 'LOOP',
 'PARADE',
 'PARKWAY',
 'PATH',
 'PLACE',
 'POINT',
 'PROMENADE',
 'RAMP',
 'RIDGE',
 'RISE',
 'ROAD',
 'ROUTE',
 'RUN',
 'SQUARE',
 'STREET',
 'STRIP',
 'TERRACE',
 'THROUGHWAY',
 'TRACK',
 'TRAIL',
 'TUNNEL',
 'WALK',
 'WAY',
 'WEST',
 'WYND',
 nan}

In [123]:
# check the value inside in the road_type column
rord_tpint_list = join2_df["ROAD_TYPE_INT"].values.tolist()
rord_tpint_list = set(rord_tpint_list)
rord_tpint_list

{' ',
 'ACCESS',
 'ALLEY',
 'ARCADE',
 'AVENUE',
 'AVENUE SERVICE ROAD',
 'BEND',
 'BOULEVARD',
 'BOULEVARDE',
 'BREAK',
 'BYPASS',
 'CAUSEWAY',
 'CENTRE',
 'CHASE',
 'CIRCLE',
 'CIRCUIT',
 'CLOSE',
 'CONNECTION',
 'COURT',
 'COURT SERVICE ROAD',
 'CRESCENT',
 'CROSSING',
 'CUTTING',
 'DEVIATION',
 'DIVIDE',
 'DRIVE',
 'DRIVE SERVICE ROAD',
 'ESPLANADE',
 'FIREBREAK',
 'FIRELINE',
 'FIRETRAIL',
 'FREEWAY',
 'FREEWAY SERVICE ROAD',
 'GARDENS',
 'GATEWAY',
 'GLADE',
 'GLEN',
 'GREEN',
 'GROVE',
 'HEIGHTS',
 'HIGHWAY',
 'HIGHWAY SERVICE ROAD',
 'HILL',
 'HUB',
 'ISLAND',
 'LANDING',
 'LANE',
 'LINK',
 'LOOP',
 'MALL',
 'MEWS',
 'NOOK',
 'PARADE',
 'PARADE SERVICE ROAD',
 'PARKWAY',
 'PASS',
 'PLACE',
 'PLAZA',
 'POINT',
 'PROMENADE',
 'QUADRANT',
 'RAMP',
 'RETREAT',
 'RIDGE',
 'RISE',
 'RISE SERVICE ROAD',
 'ROAD',
 'ROAD SERVICE ROAD',
 'ROUTE',
 'ROW',
 'RUN',
 'SERVICE ROAD',
 'SQUARE',
 'STREET',
 'STREET SERVICE ROAD',
 'STRIP',
 'TERRACE',
 'THROUGHWAY',
 'TRACK',
 'TRAIL',
 'TUNNE

In [124]:
# check the distinct value between these two lists
rord_tp_list - rord_tpint_list

{'CONCOURSE', 'EAST', 'GRANGE', 'PATH', 'WEST'}

These four type shows on the rord_tp_list but not in the rord_tpint_list.

In [125]:
# check the distinct value between these two lists
rord_tpint_list - rord_tp_list

{'ACCESS',
 'ARCADE',
 'AVENUE SERVICE ROAD',
 'CHASE',
 'CIRCLE',
 'CONNECTION',
 'COURT SERVICE ROAD',
 'CROSSING',
 'DEVIATION',
 'DIVIDE',
 'DRIVE SERVICE ROAD',
 'FIREBREAK',
 'FIRETRAIL',
 'FREEWAY SERVICE ROAD',
 'GARDENS',
 'GATEWAY',
 'GLADE',
 'GLEN',
 'HEIGHTS',
 'HIGHWAY SERVICE ROAD',
 'HILL',
 'HUB',
 'ISLAND',
 'LANDING',
 'MALL',
 'MEWS',
 'NOOK',
 'PARADE SERVICE ROAD',
 'PASS',
 'PLAZA',
 'QUADRANT',
 'RETREAT',
 'RISE SERVICE ROAD',
 'ROAD SERVICE ROAD',
 'ROW',
 'SERVICE ROAD',
 'STREET SERVICE ROAD',
 'VIEW',
 'VIEWS',
 'WAY SERVICE ROAD',
 'WHARF'}

However, it has too many items show on the rord_tpint_list but not in the rord_tp_list. So, before discussing with client, these rows will be removed. After checking more detail, then it may insert the correct data in here.

In [126]:
# remove the null value rows in the join2_df when the column is ROAD_TYPE
idx = join2_df[join2_df["ROAD_TYPE"].isnull()].index.values

for index in idx:
    join2_df.drop([index], inplace = True)

In [127]:
# double check does it have any null column in the join2_df
join2_df.isna().any()

ACCIDENT_NO             False
ACCIDENTDATE            False
ACCIDENTTIME            False
ACCIDENT_TYPE           False
Accident Type Desc      False
DAY_OF_WEEK             False
Day Week Description    False
DCA_CODE                False
DCA Description         False
LIGHT_CONDITION         False
Light Condition Desc    False
NO_OF_VEHICLES          False
NO_PERSONS              False
NO_PERSONS_INJ_2        False
NO_PERSONS_INJ_3        False
NO_PERSONS_KILLED       False
NO_PERSONS_NOT_INJ      False
POLICE_ATTEND           False
ROAD_GEOMETRY           False
Road Geometry Desc      False
SEVERITY                False
SPEED_ZONE              False
ROAD_ROUTE_1            False
ROAD_ROUTE_1_DES        False
ROAD_NAME               False
ROAD_TYPE               False
ROAD_NAME_INT            True
ROAD_TYPE_INT            True
DIRECTION_LOCATION      False
NODE_TYPE               False
LGA_NAME                False
Lga Name All            False
Region Name             False
Lat       

It still has the missing value in the ROAD_NAME_INT, and ROAD_TYPE_INT column.

In [128]:
# check the number of missing value in ROAD_TYPE_INT column
join2_df[join2_df["ROAD_TYPE_INT"].isnull()]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
238    T20140000642   2014-10-01     22.22.00              1   
280    T20140000736   2014-12-01     14.04.00              1   
477    T20140001157   2014-01-18     13.30.00              8   
495    T20140001199   2014-01-19     15.04.00              1   
512    T20140001232   2014-01-16     12.15.00              1   
...             ...          ...          ...            ...   
51512  T20170024675   2017-12-26     13.30.00              1   
51520  T20170024694   2017-12-26     15.21.00              1   
51565  T20170024804   2017-12-28     17.27.00              4   
51616  T20170024930   2017-12-30     21.40.00              4   
51621  T20170024943   2017-12-31     09.35.00              6   

                      Accident Type Desc  DAY_OF_WEEK Day Week Description  \
238               Collision with vehicle            6               Friday   
280               Collision with vehicle            1               Sunday   
477    No collision and no object struck            7             Saturday   
495               Collision with vehicle            1               Sunday   
512               Collision with vehicle            5             Thursday   
...                                  ...          ...                  ...   
51512             Collision with vehicle            3              Tuesday   
51520             Collision with vehicle            3              Tuesday   
51565      Collision with a fixed object            5             Thursday   
51616      Collision with a fixed object            7             Saturday   
51621  Vehicle overturned (no collision)            1               Sunday   

       DCA_CODE                                    DCA Description  \
238         132               RIGHT REAR.                            
280         116      LEFT NEAR (INTERSECTIONS ONLY)                  
477         182       OFF CARRIAGEWAY ON LEFT BEND                   
495         160  VEHICLE COLLIDES WITH VEHICLE PARKED ON LEFT O...   
512         120         HEAD ON (NOT OVERTAKING)                     
...         ...                                                ...   
51512       132               RIGHT REAR.                            
51520       120         HEAD ON (NOT OVERTAKING)                     
51565       171  LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICL...   
51616       171  LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICL...   
51621       182       OFF CARRIAGEWAY ON LEFT BEND                   

       LIGHT_CONDITION  ...   ROAD_NAME_INT  ROAD_TYPE_INT  \
238                  5  ...       THE EYRIE            NaN   
280                  1  ...             NaN            NaN   
477                  1  ...         ROAD 24            NaN   
495                  1  ...       THE GROVE            NaN   
512                  1  ...         ROAD 15            NaN   
...                ...  ...             ...            ...   
51512                1  ...             NaN            NaN   
51520                1  ...             NaN            NaN   
51565                1  ...             NaN            NaN   
51616                5  ...          ROAD 7            NaN   
51621                1  ...  THE BOULEVARDE            NaN   

       DIRECTION_LOCATION  NODE_TYPE      LGA_NAME  Lga Name All  \
238                     N          N  YARRA RANGES  YARRA RANGES   
280                    NK          I        MONASH        MONASH   
477                    SW          N        ALPINE        ALPINE   
495                     N          N        MELTON        MELTON   
512                     W          N  YARRA RANGES  YARRA RANGES   
...                   ...        ...           ...           ...   
51512                  NK          N     MAROONDAH     MAROONDAH   
51520                  NK          N          HUME          HUME   
51565                  NK          N  YARRA RANGES  YARRA RANGES   
51616                  NE          N

In the definition, the ROAD_TYPE and ROAD_TYPE_INT are very similar data, which ROAD_TYPE_INT contains more detail. After checking the missing value in the ROAD_TYPE_INT column, it has around 469 rows containing the missing value. Under the considering between ROAD_TYPE and ROAD_TYPE_INT two columns, this time can use the borad information to analysis the ROAD_TYPE data having what kind of relationship within the accident.

Therefore, the ROAD_TYPE_INT will be removed to keep more rows data to analysis.

In [129]:
# delete the ROAD_TYPE_INT column
del join2_df["ROAD_TYPE_INT"]

In [130]:
# check the number of missing value in ROAD_NAME_INT column
join2_df[join2_df["ROAD_NAME_INT"].isnull()]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
280    T20140000736   2014-12-01     14.04.00              1   
1707   T20140003617   2014-02-20     07.00.00              4   
7164   T20140014378   2014-12-07     11.30.00              4   
7851   T20140015753   2014-07-27     13.30.00              1   
7942   T20140015945   2014-07-31     08.15.00              2   
...             ...          ...          ...            ...   
51481  T20170024595   2017-12-24     16.35.00              1   
51509  T20170024670   2017-12-15     16.30.00              1   
51512  T20170024675   2017-12-26     13.30.00              1   
51520  T20170024694   2017-12-26     15.21.00              1   
51565  T20170024804   2017-12-28     17.27.00              4   

                  Accident Type Desc  DAY_OF_WEEK Day Week Description  \
280           Collision with vehicle            1               Sunday   
1707   Collision with a fixed object            5             Thursday   
7164   Collision with a fixed object            7             Saturday   
7851          Collision with vehicle            1               Sunday   
7942               Struck Pedestrian            5             Thursday   
...                              ...          ...                  ...   
51481         Collision with vehicle            0               Sunday   
51509         Collision with vehicle            6               Friday   
51512         Collision with vehicle            3              Tuesday   
51520         Collision with vehicle            3              Tuesday   
51565  Collision with a fixed object            5             Thursday   

       DCA_CODE                                    DCA Description  \
280         116      LEFT NEAR (INTERSECTIONS ONLY)                  
1707        171  LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICL...   
7164        171  LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICL...   
7851        130     REAR END(VEHICLES IN SAME LANE)                  
7942        107  PED ON FOOTHPATH STRUCK BY VEHENTERING/LEAVING...   
...         ...                                                ...   
51481       130     REAR END(VEHICLES IN SAME LANE)                  
51509       137           LEFT TURN SIDESWIPE                        
51512       132               RIGHT REAR.                            
51520       120         HEAD ON (NOT OVERTAKING)                     
51565       171  LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICL...   

       LIGHT_CONDITION  ... ROAD_TYPE  ROAD_NAME_INT  DIRECTION_LOCATION  \
280                  1  ...      RAMP            NaN                  NK   
1707                 2  ...     DRIVE            NaN                  NK   
7164                 1  ...     TRACK            NaN                  NK   
7851                 1  ...      RAMP            NaN                  NK   
7942                 1  ...      LANE            NaN                  NK   
...                ...  ...       ...            ...                 ...   
51481                1  ...   HIGHWAY            NaN                  NK   
51509                1  ...      ROAD            NaN                  NK   
51512                1  ...      ROAD            NaN                  NK   
51520                1  ...      ROAD            NaN                  NK   
51565                1  ...   HIGHWAY            NaN                  NK   

       NODE_TYPE      LGA_NAME       Lga Name All  \
280            I        MONASH             MONASH   
1707           N      BALLARAT  PYRENEES,BALLARAT   
7164           N    WELLINGTON         WELLINGTON   
7851           I         CASEY              CASEY   
7942           N     MELBOURNE          MELBOURNE   
...          ...           ...                ...   
51481          N          KNOX               KNOX   
51509          I       WYNDHAM            WYNDHAM   
51512          N     MAROONDAH          MAROONDAH   
51520          N          HUME               HUME   
51565        

In [131]:
# remove the null value rows in the join2_df when the column is ROAD_NAME_INT
idx = join2_df[join2_df["ROAD_NAME_INT"].isnull()].index.values

for index in idx:
    join2_df.drop([index], inplace = True)

In [132]:
# remove the " " rows in the join2_df when the column is ROAD_NAME
idx = join2_df[join2_df["ROAD_NAME"] == " "].index.values

for index in idx:
    join2_df.drop([index], inplace = True)

In [133]:
# double check the null value data in road_name column
join2_df[join2_df["ROAD_NAME"] == " "]

Empty DataFrame
Columns: [ACCIDENT_NO, ACCIDENTDATE, ACCIDENTTIME, ACCIDENT_TYPE, Accident Type Desc, DAY_OF_WEEK, Day Week Description, DCA_CODE, DCA Description, LIGHT_CONDITION, Light Condition Desc, NO_OF_VEHICLES, NO_PERSONS, NO_PERSONS_INJ_2, NO_PERSONS_INJ_3, NO_PERSONS_KILLED, NO_PERSONS_NOT_INJ, POLICE_ATTEND, ROAD_GEOMETRY, Road Geometry Desc, SEVERITY, SPEED_ZONE, ROAD_ROUTE_1, ROAD_ROUTE_1_DES, ROAD_NAME, ROAD_TYPE, ROAD_NAME_INT, DIRECTION_LOCATION, NODE_TYPE, LGA_NAME, Lga Name All, Region Name, Lat, Long, Postcode No]
Index: []

[0 rows x 35 columns]

In [134]:
# check the null value data in the road_type column
join2_df[join2_df["ROAD_TYPE"] == " "]

Empty DataFrame
Columns: [ACCIDENT_NO, ACCIDENTDATE, ACCIDENTTIME, ACCIDENT_TYPE, Accident Type Desc, DAY_OF_WEEK, Day Week Description, DCA_CODE, DCA Description, LIGHT_CONDITION, Light Condition Desc, NO_OF_VEHICLES, NO_PERSONS, NO_PERSONS_INJ_2, NO_PERSONS_INJ_3, NO_PERSONS_KILLED, NO_PERSONS_NOT_INJ, POLICE_ATTEND, ROAD_GEOMETRY, Road Geometry Desc, SEVERITY, SPEED_ZONE, ROAD_ROUTE_1, ROAD_ROUTE_1_DES, ROAD_NAME, ROAD_TYPE, ROAD_NAME_INT, DIRECTION_LOCATION, NODE_TYPE, LGA_NAME, Lga Name All, Region Name, Lat, Long, Postcode No]
Index: []

[0 rows x 35 columns]

In [135]:
# combine the information
join2_df["ROAD_NAME_TYPE"] = join2_df["ROAD_NAME"] + " " + join2_df["ROAD_TYPE"]
join2_df[:5]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
0  T20140000003   2014-01-01     00.30.00              6   
1  T20140000006   2014-01-01     01.30.00              4   
2  T20140000007   2014-01-01     03.20.00              1   
3  T20140000011   2014-01-01     03.35.00              1   
4  T20140000017   2014-01-01     08.25.00              1   

                  Accident Type Desc  DAY_OF_WEEK Day Week Description  \
0  Vehicle overturned (no collision)            4            Wednesday   
1      Collision with a fixed object            4            Wednesday   
2             Collision with vehicle            4            Wednesday   
3             Collision with vehicle            4            Wednesday   
4             Collision with vehicle            4            Wednesday   

   DCA_CODE                                    DCA Description  \
0       180      OFF CARRIAGEWAY ON RIGHT BEND                   
1       171  LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICL...   
2       110    CROSS TRAFFIC(INTERSECTIONS ONLY)                 
3       160  VEHICLE COLLIDES WITH VEHICLE PARKED ON LEFT O...   
4       160  VEHICLE COLLIDES WITH VEHICLE PARKED ON LEFT O...   

   LIGHT_CONDITION  ... ROAD_NAME_INT  DIRECTION_LOCATION  NODE_TYPE  \
0                3  ...     GRAINGERS                  SE          N   
1                5  ...  SPRING CREEK                   W          N   
2                3  ...    WELLINGTON                   S          I   
3                3  ...       PARINGA                   W          I   
4                1  ...       BROOKES                   S          N   

      LGA_NAME     Lga Name All                     Region Name       Lat  \
0  MARIBYRNONG      MARIBYRNONG  METROPOLITAN NORTH WEST REGION -37.80202   
1   WELLINGTON       WELLINGTON                  EASTERN REGION -38.45802   
2    MELBOURNE  YARRA,MELBOURNE  METROPOLITAN NORTH WEST REGION -37.81755   
3         KNOX             KNOX  METROPOLITAN SOUTH EAST REGION -37.89864   
4        YARRA            YARRA  METROPOLITAN NORTH WEST REGION -37.78711   

        Long  Postcode No            ROAD_NAME_TYPE  
0  144.88100         3012   FOOTSCRAY-SUNSHINE ROAD  
1  146.70151         3971         GREIGS CREEK ROAD  
2  144.99001         3121  HODDLE STREET -PUNT ROAD  
3  145.28114         3156       KOOLAMARA BOULEVARD  
4  144.97684         3068          NICHOLSON STREET  

[5 rows x 36 columns]

In [136]:
# change the column order
col_list = join2_df.columns.to_list()
col_list.insert(26, "ROAD_NAME_TYPE")
col_list.pop()

'ROAD_NAME_TYPE'

In [137]:
# reorder the column name in the acc_lo_df
join2_df = join2_df[col_list]
join2_df[:5]

ACCIDENT_NO ACCIDENTDATE ACCIDENTTIME  ACCIDENT_TYPE  \
0  T20140000003   2014-01-01     00.30.00              6   
1  T20140000006   2014-01-01     01.30.00              4   
2  T20140000007   2014-01-01     03.20.00              1   
3  T20140000011   2014-01-01     03.35.00              1   
4  T20140000017   2014-01-01     08.25.00              1   

                  Accident Type Desc  DAY_OF_WEEK Day Week Description  \
0  Vehicle overturned (no collision)            4            Wednesday   
1      Collision with a fixed object            4            Wednesday   
2             Collision with vehicle            4            Wednesday   
3             Collision with vehicle            4            Wednesday   
4             Collision with vehicle            4            Wednesday   

   DCA_CODE                                    DCA Description  \
0       180      OFF CARRIAGEWAY ON RIGHT BEND                   
1       171  LEFT OFF CARRIAGEWAY INTO OBJECT/PARKED VEHICL...   
2       110    CROSS TRAFFIC(INTERSECTIONS ONLY)                 
3       160  VEHICLE COLLIDES WITH VEHICLE PARKED ON LEFT O...   
4       160  VEHICLE COLLIDES WITH VEHICLE PARKED ON LEFT O...   

   LIGHT_CONDITION  ...            ROAD_NAME_TYPE  ROAD_NAME_INT  \
0                3  ...   FOOTSCRAY-SUNSHINE ROAD      GRAINGERS   
1                5  ...         GREIGS CREEK ROAD   SPRING CREEK   
2                3  ...  HODDLE STREET -PUNT ROAD     WELLINGTON   
3                3  ...       KOOLAMARA BOULEVARD        PARINGA   
4                1  ...          NICHOLSON STREET        BROOKES   

   DIRECTION_LOCATION  NODE_TYPE     LGA_NAME     Lga Name All  \
0                  SE          N  MARIBYRNONG      MARIBYRNONG   
1                   W          N   WELLINGTON       WELLINGTON   
2                   S          I    MELBOURNE  YARRA,MELBOURNE   
3                   W          I         KNOX             KNOX   
4                   S          N        YARRA            YARRA   

                      Region Name       Lat       Long Postcode No  
0  METROPOLITAN NORTH WEST REGION -37.80202  144.88100        3012  
1                  EASTERN REGION -38.45802  146.70151        3971  
2  METROPOLITAN NORTH WEST REGION -37.81755  144.99001        3121  
3  METROPOLITAN SOUTH EAST REGION -37.89864  145.28114        3156  
4  METROPOLITAN NORTH WEST REGION -37.78711  144.97684        3068  

[5 rows x 36 columns]

### Check for the anonymous

In [138]:
join2_df.describe()

ACCIDENT_TYPE   DAY_OF_WEEK      DCA_CODE  LIGHT_CONDITION  \
count   47016.000000  47016.000000  47016.000000     47016.000000   
mean        2.231793      4.044729    138.992981         1.890590   
std         2.012393      2.015440     26.443788         1.608676   
min         1.000000      0.000000    100.000000         1.000000   
25%         1.000000      2.000000    120.000000         1.000000   
50%         1.000000      4.000000    130.000000         1.000000   
75%         4.000000      6.000000    170.000000         2.000000   
max         9.000000      7.000000    199.000000         9.000000   

       NO_OF_VEHICLES    NO_PERSONS  NO_PERSONS_INJ_2  NO_PERSONS_INJ_3  \
count    47016.000000  47016.000000      47016.000000      47016.000000   
mean         1.809809      2.402969          0.335418          0.913391   
std          0.742896      1.552837          0.592815          0.766569   
min          1.000000      1.000000          0.000000          0.000000   
25%          1.000000      2.000000          0.000000          0.000000   
50%          2.000000      2.000000          0.000000          1.000000   
75%          2.000000      3.000000          1.000000          1.000000   
max         14.000000     89.000000         16.000000         25.000000   

       NO_PERSONS_KILLED  NO_PERSONS_NOT_INJ  POLICE_ATTEND  ROAD_GEOMETRY  \
count       47016.000000        47016.000000   47016.000000   47016.000000   
mean            0.019632            1.133976       1.287859       3.297516   
std             0.152882            1.369120       0.656743       1.774651   
min             0.000000            0.000000       1.000000       1.000000   
25%             0.000000            0.000000       1.000000       2.000000   
50%             0.000000            1.000000       1.000000       4.000000   
75%             0.000000            1.000000       2.000000       5.000000   
max             4.000000           87.000000       9.000000       9.000000   

           SEVERITY    SPEED_ZONE  ROAD_ROUTE_1           Lat          Long  \
count  47016.000000  47016.000000  47016.000000  47016.000000  47016.000000   
mean       2.676642    127.827165   6461.305258    -37.707149    144.972474   
std        0.504810    228.110224   2963.449102      0.574247      0.811569   
min        1.000000     30.000000   2000.000000    -39.016350    140.966480   
25%        2.000000     60.000000   4890.000000    -37.949883    144.854662   
50%        3.000000     60.000000   5786.000000    -37.816135    145.015795   
75%        3.000000     80.000000   9999.000000    -37.697840    145.207200   
max        4.000000    999.000000   9999.000000    -34.130450    149.749840   

        Postcode No  
count  47016.000000  
mean    3311.731134  
std      302.149971  
min     3000.000000  
25%     3074.000000  
50%     3175.000000  
75%     3550.000000  
max     3996.000000

It looks not contain any anoymous data in the join2_df.

### Check with the string based data type columns

In [139]:
join2_df.dtypes

ACCIDENT_NO                     object
ACCIDENTDATE            datetime64[ns]
ACCIDENTTIME                    object
ACCIDENT_TYPE                    int64
Accident Type Desc              object
DAY_OF_WEEK                      int64
Day Week Description            object
DCA_CODE                         int64
DCA Description                 object
LIGHT_CONDITION                  int64
Light Condition Desc            object
NO_OF_VEHICLES                   int64
NO_PERSONS                       int64
NO_PERSONS_INJ_2                 int64
NO_PERSONS_INJ_3                 int64
NO_PERSONS_KILLED                int64
NO_PERSONS_NOT_INJ               int64
POLICE_ATTEND                    int64
ROAD_GEOMETRY                    int64
Road Geometry Desc              object
SEVERITY                         int64
SPEED_ZONE                       int64
ROAD_ROUTE_1                   float64
ROAD_ROUTE_1_DES                object
ROAD_NAME                       object
ROAD_TYPE                

In [140]:
# store the object data type column name into obj_list
obj_list = join2_df.select_dtypes(include=["object"]).columns.tolist()

In [141]:
# group the year to look at the how many rows at each year
for name in obj_list:
    print(join2_df.groupby(name)[name].count())
    print("----------------------------------")

ACCIDENT_NO
T20140000003    1
T20140000006    1
T20140000007    1
T20140000011    1
T20140000017    1
               ..
T20180002575    1
T20180002725    1
T20180002839    1
T20180002942    1
T20180003263    1
Name: ACCIDENT_NO, Length: 47016, dtype: int64
----------------------------------
ACCIDENTTIME
00.00.00    32
00.01.00    29
00.02.00     7
00.03.00     4
00.04.00     4
            ..
23.55.00    20
23.56.00     2
23.57.00     3
23.58.00     3
23.59.00     8
Name: ACCIDENTTIME, Length: 1393, dtype: int64
----------------------------------
Accident Type Desc
Collision with a fixed object         7154
Collision with vehicle               29995
Fall from or in moving vehicle         209
No collision and no object struck     2398
Other accident                          38
Struck Pedestrian                     4039
Struck animal                          482
Vehicle overturned (no collision)     2301
collision with some other object       400
Name: Accident Type Desc, dtype: int64
---

In the LGA_NAME and Lga Name All has some pattern of the value, which is the value containing the parentheses. Therefore, these tow columns need to remove the parentheses of each containing parentheses value.

In [142]:
# remove the parentheses in the LGA_NAME column
join2_df["LGA_NAME"] = join2_df["LGA_NAME"].str.replace(r"[()]","")

In [143]:
# check the result after removing the parentheses in the LGA_NAME column
join2_df.groupby("LGA_NAME")["LGA_NAME"].count()

LGA_NAME
ALPINE           159
ARARAT           114
BALLARAT         829
BANYULE          671
BASS COAST       261
                ... 
WODONGA          205
WYNDHAM         1043
YARRA           1124
YARRA RANGES    1424
YARRIAMBIACK      33
Name: LGA_NAME, Length: 84, dtype: int64

In [144]:
# remove the parentheses in the Lga Name All column
join2_df["Lga Name All"] = join2_df["Lga Name All"].str.replace(r"[()]","")

In [145]:
# check the result after removing the parentheses in the Lga Name All column
join2_df.groupby("Lga Name All")["Lga Name All"].count()

Lga Name All
ALPINE                             158
ARARAT                             107
BALLARAT                           814
BANYULE                            626
BASS COAST                         256
                                  ... 
YARRA,MELBOURNE,MORELAND             1
YARRA,MORELAND                      33
YARRIAMBIACK                        33
YARRIAMBIACK,BULOKE                  1
YARRIAMBIACK,NORTHERN GRAMPIANS      1
Name: Lga Name All, Length: 205, dtype: int64

In [146]:
# check the all of column have containing the null value or not
for name in obj_list:
    print(join2_df[name].isnull().values.any())
    print("----------------------------------")

False
----------------------------------
False
----------------------------------
False
----------------------------------
False
----------------------------------
False
----------------------------------
False
----------------------------------
False
----------------------------------
False
----------------------------------
False
----------------------------------
False
----------------------------------
False
----------------------------------
False
----------------------------------
False
----------------------------------
False
----------------------------------
False
----------------------------------
False
----------------------------------
False
----------------------------------


All of the columns do not contain the null value.

## Save the dataframe into the excel. file

In [147]:
join2_df.to_excel("cleandata_accident.xlsx", index = False) 